## Importing of Libraries


In [1]:
import time
from copy import deepcopy

import numpy as np
import torch
from dlordinal.datasets import FGNet
from dlordinal.losses import OrdinalEcocDistanceLoss
from dlordinal.models import resnet18_ecoc
from sklearn.metrics import (accuracy_score, cohen_kappa_score,
                             confusion_matrix, mean_absolute_error)
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.utils import class_weight
from torch import cuda
from torch.optim import Adam
from torch.utils.data import DataLoader, Subset
from torchvision.datasets import ImageFolder
from torchvision.transforms import Compose, ToTensor
from tqdm import tqdm

## Load and preprocess of FGNet dataset

First, we present the configuration parameters for the experimentation and the number of workers for the *DataLoader*, which defines the number of subprocesses to use for data loading. In this specific case, it refers to the images.

In [2]:
optimiser_params = {
    'lr': 1e-3,
    'bs': 200,
    'epochs': 5,
    's': 2,
    'c': 0.2,
    'beta': 0.5
}

workers = 3

Now we use the *FGNet* method to download and preprocess the images. Once that is done with the training data, we create a validation partition comprising 15% of the data using the *StratifiedShuffleSplit* method. Finally, with all the partitions, we load the images using a method called *DataLoader*.

In [3]:
fgnet = FGNet(root="./datasets/fgnet", download=True, process_data=True)

complete_train_data = ImageFolder(
    root="./datasets/fgnet/FGNET/train", transform=Compose([ToTensor()])
)
test_data = ImageFolder(
    root="./datasets/fgnet/FGNET/test", transform=Compose([ToTensor()])
)

num_classes = len(complete_train_data.classes)
classes = complete_train_data.classes
targets = complete_train_data.targets

# Create a validation split
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.15, random_state=0)
sss_splits = list(
    sss.split(X=np.zeros(len(complete_train_data)), y=complete_train_data.targets)
)
train_idx, val_idx = sss_splits[0]

# Create subsets for training and validation
train_data = Subset(complete_train_data, train_idx)
val_data = Subset(complete_train_data, val_idx)

# Get CUDA device
device = "cuda" if cuda.is_available() else "cpu"
print(f"Using {device} device")

# Create dataloaders
train_dataloader = DataLoader(
    train_data, batch_size=optimiser_params["bs"], shuffle=True, num_workers=workers
)
val_dataloader = DataLoader(
    val_data, batch_size=optimiser_params["bs"], shuffle=True, num_workers=workers
)
test_dataloader = DataLoader(
    test_data, batch_size=optimiser_params["bs"], shuffle=False, num_workers=workers
)

# Get image shape
img_shape = None
for X, _ in train_dataloader:
    img_shape = list(X.shape[1:])
    break
print(f"Detected image shape: {img_shape}")

# Define class weights for imbalanced datasets
class_weights = class_weight.compute_class_weight(
    "balanced", classes=[int(c) for c in classes], y=targets
)
print(f"{class_weights=}")
class_weights = (
    torch.from_numpy(class_weights).float().to(device)
)  # Transform to Tensor

Files already downloaded and verified
Files already processed and verified
Files already split and verified
Using cuda device
Detected image shape: [3, 128, 128]
class_weights=array([1.5       , 0.55165289, 1.01136364, 0.84493671, 1.0511811 ,
       2.51886792])


## Model and optimiser

We are using a modified version of the *ResNet* architecture, specifically designed for the loss function explained in the next section. In this case, the *ResNet* model is not pretrained with *ImageNet*, so we will need to undergo an extensive learning process.

To adapt the outputs of the model to this, the final fully-connected block is substituted by $Q-1$ fully-connected blocks [1], each one with a single output unit with sigmoid activation.

As an alternative to the *ResNet* architecture, you can use the *VGG* architecture, which has also been implemented to work with the loss function explained in the following sections.

Finally, we define the *Adam* optimiser, which is used to adjust the network's weights and minimize the error of a loss function.

[1]: Barbero-Gómez, J., Gutiérrez, P. A., & Hervás-Martínez, C. (2022). *Error-correcting output codes in the framework of deep ordinal classification.* Neural Processing Letters, 1-32. Springer.

In [4]:
model = resnet18_ecoc(num_classes=num_classes, activation_function='relu').to(device)

# Optimizer
optimizer = Adam(model.parameters(), lr=optimiser_params['lr'])

## Loss Function

The original $Q$-class ordinal problem is decomposed into $Q-1$ binary decision problems, what is known as Ordinal Binary Decomposition (ODB) [1]. So the categorical cross-entropy has been substituted by the Mean Squared Error loss because it copes better with the distance function used for the Error-Conecting Output Codes (ECOC) decision:

$$
\ell = \frac{1}{N} ∑_{i=1}^N ∑_{k=1}^{Q-1} (\mathbf{1} \{y_i \succ \mathcal{C}_k\} - P(y_i \succ \mathcal{C}_k | x_i))^2
$$

where $\mathbf{1} \{y_i \succ \mathcal{C}_k\}$ is the indicator function that is equal to 1 when $y_i \succ \mathcal{C}_k$ and 0 otherwise, and $P(y_i \succ \mathcal{C}_k | x_i)$ is the probability that $y_i \succ \mathcal{C}_k$ predicted by the network given a sample.

[1]: Barbero-Gómez, J., Gutiérrez, P. A., & Hervás-Martínez, C. (2022). *Error-correcting output codes in the framework of deep ordinal classification.* Neural Processing Letters, 1-32. Springer. doi.org/10.1007/s11063-022-10824-7

In [5]:
loss_fn = OrdinalEcocDistanceLoss(
    num_classes=num_classes, class_weights=class_weights, device=device
)

## Metrics

In [6]:
# Metrics computation


def compute_metrics(y_true: np.ndarray, 
    y_pred: np.ndarray, 
    num_classes: int):

    if len(y_true.shape) > 1:
        y_true = np.argmax(y_true, axis=1)

    if len(y_pred.shape) > 1:
        y_pred = np.argmax(y_pred, axis=1)

    labels = range(0, num_classes)

    # Metrics calculation
    qwk = cohen_kappa_score(y_true, y_pred, weights='quadratic', labels=labels)
    ms = minimum_sensitivity(y_true, y_pred, labels=labels)
    mae = mean_absolute_error(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)
    off1 = accuracy_off1(y_true, y_pred, labels=labels)
    conf_mat = confusion_matrix(y_true, y_pred, labels=labels)

    metrics = {
        'QWK': qwk,
        'MS': ms,
        'MAE': mae,
        'CCR': acc,
        '1-off': off1,
        'Confusion matrix': conf_mat
    }

    return metrics


def _compute_sensitivities(y_true, y_pred, labels=None):
	if len(y_true.shape) > 1:
		y_true = np.argmax(y_true, axis=1)
	if len(y_pred.shape) > 1:
		y_pred = np.argmax(y_pred, axis=1)

	conf_mat = confusion_matrix(y_true, y_pred, labels=labels)

	sum = np.sum(conf_mat, axis=1)
	mask = np.eye(conf_mat.shape[0], conf_mat.shape[1])
	correct = np.sum(conf_mat * mask, axis=1)
	sensitivities = correct / sum

	sensitivities = sensitivities[~np.isnan(sensitivities)]

	return sensitivities


def minimum_sensitivity(y_true, y_pred, labels=None):
	return np.min(_compute_sensitivities(y_true, y_pred, labels=labels))


def accuracy_off1(y_true, y_pred, labels=None):
	if len(y_true.shape) > 1:
		y_true = np.argmax(y_true, axis=1)
	if len(y_pred.shape) > 1:
		y_pred = np.argmax(y_pred, axis=1)

	conf_mat = confusion_matrix(y_true, y_pred, labels=labels)
	n = conf_mat.shape[0]
	mask = np.eye(n, n) + np.eye(n, n, k=1), + np.eye(n, n, k=-1)
	correct = mask * conf_mat

	return 1.0 * np.sum(correct) / np.sum(conf_mat)


def print_metrics(metrics):
    print("")
    print('Confusion matrix :\n{}'.format(metrics['Confusion matrix']))
    print("")
    print('MS: {:.4f}'.format(metrics['MS']))
    print("")
    print('QWK: {:.4f}'.format(metrics['QWK']))
    print("")
    print('MAE: {:.4f}'.format(metrics['MAE']))
    print("")
    print('CCR: {:.4f}'.format(metrics['CCR']))
    print("")
    print('1-off: {:.4f}'.format(metrics['1-off']))

## Training process

In [7]:
def train(
    dataloader: torch.utils.data.DataLoader,
    model: torch.nn.Module,
    loss_fn: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    H: dict,
    num_classes: int,
):  # H: dict
    num_batches = len(dataloader)
    size = len(dataloader.dataset)
    progress_bar = tqdm(total=num_batches, ncols=100, position=0, desc="Train progress")
    model.train()
    mean_loss, accuracy = 0, 0
    y_pred, y_true = None, None

    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)  # Inputs and labels to device

        # Compute prediction error and accuracy of the training process
        pred = model(X)
        print(pred)
        print(y)
        loss = loss_fn(pred, y)

        mean_loss += loss
        accuracy += (pred.argmax(1) == y).type(torch.float).sum().item()

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Stack predictions and true labels to determine the confusion matrix
        pred_np = pred.argmax(1).cpu().detach().numpy()
        true_np = y.cpu().detach().numpy()
        if y_pred is None:
            y_pred = pred_np
        else:
            y_pred = np.concatenate((y_pred, pred_np))

        if y_true is None:
            y_true = true_np
        else:
            y_true = np.concatenate((y_true, true_np))

        # Update progress bar
        progress_bar.set_postfix(loss=loss.item(), accuracy=accuracy)
        progress_bar.update(1)

    accuracy /= size
    mean_loss /= num_batches

    H["train_loss"].append(loss.cpu().detach().numpy())
    H["train_acc"].append(accuracy)

    # Confusion matrix for training
    labels = range(0, num_classes)
    conf_mat = confusion_matrix(y_true, y_pred, labels=labels)
    print("")
    print("Train Confusion matrix :\n{}".format(conf_mat))
    print("")

    return accuracy, mean_loss

## Testing process

In [8]:
def test(
    test_dataloader: torch.utils.data.DataLoader,
    model: torch.nn.Module,
    loss_fn: torch.nn.Module,
    device: torch.device,
    num_classes: int,
):
    num_batches = len(test_dataloader)
    progress_bar = tqdm(total=num_batches, ncols=100, position=0, desc="Test progress")
    model.eval()
    test_loss = 0
    y_pred, y_true = None, None

    with torch.no_grad():
        for batch, (X, y) in enumerate(test_dataloader):
            X, y = X.to(device), y.to(device)  # inputs and labels to device
            pred = model(X)
            test_loss += loss_fn(pred, y).item()

            # Stack predictions and true labels
            pred_np = pred.argmax(1).cpu().detach().numpy()
            true_np = y.cpu().detach().numpy()
            if y_pred is None:
                y_pred = pred_np
            else:
                y_pred = np.concatenate((y_pred, pred_np))

            if y_true is None:
                y_true = true_np
            else:
                y_true = np.concatenate((y_true, true_np))

            # Update progress bar
            progress_bar.set_postfix(loss=test_loss / (batch + 1))
            progress_bar.update(1)

    test_loss /= num_batches
    metrics = compute_metrics(y_true, y_pred, num_classes)
    print_metrics(metrics)

    return metrics, test_loss

## Validation process

In [10]:
def validate(
    dataloader: torch.utils.data.DataLoader,
    model: torch.nn.Module,
    loss_fn: torch.nn.Module,
    device: torch.device,
    H: dict,
    num_classes: int,
):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    loss, accuracy = 0, 0
    y_pred, y_true = None, None

    with torch.no_grad():
        for batch, (X, y) in enumerate(dataloader):
            X, y = X.to(device), y.to(device)
            pred = model(X)
            loss += loss_fn(pred, y)
            accuracy += (pred.argmax(1) == y).type(torch.float).sum().item()

            pred_np = pred.argmax(1).cpu().detach().numpy()
            true_np = y.cpu().detach().numpy()
            if y_pred is None:
                y_pred = pred_np
            else:
                y_pred = np.concatenate((y_pred, pred_np))

            if y_true is None:
                y_true = true_np
            else:
                y_true = np.concatenate((y_true, true_np))

    accuracy /= size
    loss /= num_batches

    H["val_loss"].append(loss.cpu().detach().numpy())
    H["val_acc"].append(accuracy)

    metrics = compute_metrics(y_true, y_pred, num_classes)

    return metrics, accuracy, loss

## Results

In [11]:
H = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}

# To store validation metrics
validation_metrics = {}

# Definition to store best model weights
best_model_weights = model.state_dict()
best_qwk = 0.0

# Start time
start_time = time.time()

for e in range(optimiser_params["epochs"]):
    train_acc, train_loss = train(
        train_dataloader, model, loss_fn, optimizer, device, H, num_classes=num_classes
    )
    validation_metrics, val_acc, val_loss = validate(
        val_dataloader, model, loss_fn, device, H, num_classes=num_classes
    )

    if validation_metrics["QWK"] >= best_qwk:
        best_qwk = validation_metrics["QWK"]
        best_model_weights = deepcopy(model.state_dict())

    print("[INFO] EPOCH: {}/{}".format(e + 1, optimiser_params["epochs"]))
    print("Train loss: {:.6f}, Train accuracy: {:.4f}".format(train_loss, train_acc))
    print("Val loss: {:.6f}, Val accuracy: {:.4f}\n".format(val_loss, val_acc))

# Store last train error
train_error = H["train_loss"][-1]

# Restore best weights
model.load_state_dict(best_model_weights)

# Start evaluation
print("[INFO] Network evaluation ...")

test_metrics, test_loss = test(
    test_dataloader, model, loss_fn, device, num_classes=num_classes
)

# End time
end_time = time.time()
print("\n[INFO] Total training time: {:.2f}s".format(end_time - start_time))

Train progress:  25%|██████▌                   | 1/4 [00:01<00:03,  1.30s/it, accuracy=40, loss=257]

tensor([[0.4492, 0.5579, 0.4470, 0.4841, 0.3665],
        [0.4532, 0.5256, 0.4102, 0.5699, 0.3539],
        [0.5053, 0.4867, 0.3301, 0.5264, 0.3328],
        [0.4698, 0.4144, 0.3409, 0.5315, 0.3169],
        [0.4352, 0.5462, 0.3624, 0.5480, 0.4264],
        [0.4942, 0.4555, 0.4144, 0.5377, 0.4174],
        [0.4670, 0.5303, 0.3339, 0.5341, 0.4295],
        [0.4240, 0.4850, 0.4000, 0.5697, 0.4508],
        [0.4856, 0.4541, 0.3190, 0.5549, 0.4277],
        [0.4892, 0.4759, 0.4013, 0.5511, 0.4069],
        [0.4301, 0.5113, 0.2979, 0.5705, 0.4599],
        [0.4663, 0.4816, 0.3242, 0.5726, 0.3543],
        [0.4330, 0.4827, 0.4093, 0.5249, 0.3795],
        [0.4500, 0.5189, 0.3577, 0.5378, 0.3315],
        [0.4694, 0.4955, 0.4477, 0.6006, 0.4469],
        [0.4919, 0.5195, 0.3839, 0.5123, 0.4330],
        [0.4735, 0.5546, 0.3361, 0.5539, 0.4283],
        [0.4160, 0.5800, 0.3415, 0.5834, 0.3739],
        [0.4517, 0.5404, 0.3815, 0.5270, 0.4242],
        [0.4637, 0.4951, 0.3088, 0.5321, 0.4279],


Train progress:  75%|███████████████████▌      | 3/4 [00:01<00:00,  2.63it/s, accuracy=88, loss=190]

tensor([[0.8670, 0.8377, 0.8199, 0.7870, 0.8756],
        [0.5322, 0.4781, 0.3185, 0.2297, 0.0717],
        [0.7961, 0.7365, 0.6125, 0.5568, 0.5607],
        [0.6071, 0.5901, 0.2925, 0.2243, 0.0806],
        [0.6930, 0.6910, 0.4381, 0.3954, 0.2443],
        [0.5751, 0.5518, 0.3515, 0.2160, 0.0839],
        [0.5225, 0.5231, 0.3085, 0.1822, 0.0406],
        [0.6819, 0.6709, 0.4801, 0.4058, 0.2140],
        [0.5956, 0.4954, 0.2812, 0.2468, 0.1328],
        [0.8609, 0.7968, 0.6201, 0.6801, 0.7087],
        [0.9327, 0.9191, 0.8970, 0.8866, 0.9702],
        [0.5906, 0.5694, 0.3025, 0.2218, 0.0674],
        [0.6689, 0.5966, 0.4917, 0.4296, 0.1598],
        [0.6784, 0.6160, 0.4300, 0.4005, 0.1774],
        [0.5653, 0.5591, 0.2848, 0.1883, 0.0314],
        [0.4993, 0.4327, 0.1901, 0.1223, 0.0543],
        [0.5330, 0.5213, 0.2139, 0.1304, 0.0261],
        [0.6350, 0.6538, 0.4170, 0.3384, 0.1851],
        [0.6001, 0.5095, 0.2835, 0.2366, 0.1063],
        [0.8027, 0.7906, 0.7561, 0.6186, 0.5467],


Train progress: 100%|█████████████████████████| 4/4 [00:01<00:00,  2.37it/s, accuracy=95, loss=69.8]


Train Confusion matrix :
[[ 33  15   0  21   2   0]
 [115  34   1  51   4   0]
 [ 54  19   0  31   6   0]
 [ 70  39   0  27   9   0]
 [ 58  24   0  18   1   0]
 [ 24  13   0  11   0   0]]



[INFO] EPOCH: 1/5
Train loss: 185.848236, Train accuracy: 0.1397
Val loss: 133.039230, Val accuracy: 0.2645



Train progress:  50%|█████████████             | 2/4 [00:00<00:00,  3.47it/s, accuracy=45, loss=184]

tensor([[9.7006e-01, 9.7859e-01, 8.7153e-01, 6.0355e-01, 2.9696e-01],
        [9.4641e-01, 9.1541e-01, 7.1996e-01, 3.8114e-01, 1.4335e-01],
        [9.7465e-01, 9.9657e-01, 9.7543e-01, 7.0725e-01, 5.9720e-01],
        [9.2798e-01, 8.3707e-01, 5.8344e-01, 3.1683e-01, 9.8352e-02],
        [9.5771e-01, 9.7514e-01, 9.1775e-01, 5.7037e-01, 1.8870e-01],
        [8.2332e-01, 3.6968e-01, 2.4571e-01, 7.4587e-02, 5.1926e-02],
        [8.6984e-01, 5.4806e-01, 2.9197e-01, 7.2363e-02, 4.4169e-02],
        [9.2104e-01, 8.0999e-01, 6.0287e-01, 3.0732e-01, 1.3439e-01],
        [9.1269e-01, 6.2779e-01, 3.8037e-01, 1.5998e-01, 4.9149e-02],
        [7.2522e-01, 1.8753e-01, 1.5197e-01, 1.2207e-02, 2.2068e-02],
        [9.5623e-01, 9.8004e-01, 9.2924e-01, 4.6604e-01, 1.9757e-01],
        [7.7636e-01, 1.7288e-01, 6.8098e-02, 1.2132e-02, 1.5538e-02],
        [9.4765e-01, 9.1058e-01, 7.8090e-01, 3.0738e-01, 1.0335e-01],
        [8.9823e-01, 5.2422e-01, 2.3915e-01, 1.1300e-01, 6.6924e-02],
        [8.6826e-01,

Train progress:  75%|██████████████████▊      | 3/4 [00:00<00:00,  4.76it/s, accuracy=74, loss=48.8]

tensor([[9.6119e-01, 8.2901e-01, 5.0627e-01, 2.7720e-01, 6.0511e-02],
        [9.8597e-01, 9.7494e-01, 7.7288e-01, 4.7424e-01, 2.2956e-01],
        [9.6757e-01, 9.4258e-01, 7.2719e-01, 3.4602e-01, 1.6784e-01],
        [9.5010e-01, 8.3311e-01, 6.1231e-01, 4.1077e-01, 1.7585e-01],
        [9.6454e-01, 7.9019e-01, 5.5704e-01, 3.5596e-01, 1.0123e-01],
        [9.8416e-01, 9.6563e-01, 7.7567e-01, 5.0704e-01, 3.2444e-01],
        [9.1457e-01, 5.8994e-01, 4.3330e-01, 2.4136e-01, 8.8909e-02],
        [3.9845e-01, 3.6934e-02, 1.2978e-02, 2.3059e-04, 1.0338e-04],
        [9.5779e-01, 8.6055e-01, 6.0369e-01, 4.0927e-01, 9.9758e-02],
        [7.9059e-01, 5.3636e-01, 3.5500e-01, 1.0210e-01, 3.2341e-02],
        [9.7743e-01, 9.5062e-01, 7.4797e-01, 5.5852e-01, 1.6146e-01],
        [3.5851e-01, 2.4360e-02, 1.1499e-02, 1.0355e-04, 6.4774e-05],
        [9.7857e-01, 9.2264e-01, 7.5046e-01, 3.7803e-01, 8.3955e-02],
        [9.3687e-01, 8.8908e-01, 5.4592e-01, 5.1711e-01, 5.4287e-01],
        [9.6014e-01,

Train progress: 100%|█████████████████████████| 4/4 [00:00<00:00,  4.15it/s, accuracy=74, loss=48.8]



Train Confusion matrix :
[[ 69   2   0   0   0   0]
 [200   5   0   0   0   0]
 [104   6   0   0   0   0]
 [134  11   0   0   0   0]
 [ 87  14   0   0   0   0]
 [ 37  11   0   0   0   0]]

[INFO] EPOCH: 2/5
Train loss: 144.164032, Train accuracy: 0.1088
Val loss: 297.547424, Val accuracy: 0.2975



Train progress:  50%|█████████████             | 2/4 [00:00<00:00,  3.13it/s, accuracy=45, loss=123]

tensor([[9.7959e-01, 7.8909e-01, 3.9101e-01, 2.0524e-01, 4.0425e-02],
        [5.1038e-01, 1.3066e-01, 1.3538e-01, 3.7813e-02, 1.1146e-02],
        [9.8018e-01, 7.6106e-01, 3.7055e-01, 1.9389e-01, 3.9976e-02],
        [2.7577e-01, 1.2823e-01, 7.1537e-02, 3.9966e-03, 1.9616e-03],
        [8.7367e-01, 4.6360e-01, 2.4993e-01, 1.2768e-01, 3.2908e-02],
        [9.9945e-01, 9.9849e-01, 8.9622e-01, 9.2022e-01, 6.7842e-01],
        [3.1468e-01, 1.3923e-01, 1.0146e-01, 1.3457e-02, 4.5149e-03],
        [9.1419e-01, 4.0817e-01, 2.2694e-01, 7.2198e-02, 1.7402e-02],
        [9.9562e-01, 9.5974e-01, 5.6125e-01, 4.9123e-01, 8.5803e-02],
        [9.8981e-01, 9.4330e-01, 6.1254e-01, 5.0002e-01, 1.5884e-01],
        [8.6918e-01, 3.4637e-01, 1.7621e-01, 4.4784e-02, 1.0474e-02],
        [8.4379e-01, 4.3701e-01, 2.1078e-01, 5.1530e-02, 1.7327e-02],
        [9.9828e-01, 9.9626e-01, 8.9876e-01, 9.6775e-01, 8.3749e-01],
        [9.8942e-01, 8.3140e-01, 5.4221e-01, 6.7416e-01, 1.5835e-01],
        [9.4844e-01,

Train progress:  75%|██████████████████▊      | 3/4 [00:00<00:00,  4.41it/s, accuracy=70, loss=42.4]

tensor([[9.8434e-01, 8.9212e-01, 5.8046e-01, 3.4994e-01, 1.2671e-01],
        [9.8047e-01, 7.8634e-01, 6.8650e-01, 6.0664e-01, 2.2206e-01],
        [9.3476e-02, 2.6752e-01, 9.4394e-02, 7.3366e-03, 1.0280e-03],
        [9.2008e-01, 6.0031e-01, 3.3543e-01, 1.7364e-01, 4.3185e-02],
        [9.9666e-01, 9.4079e-01, 7.1564e-01, 5.7223e-01, 1.3641e-01],
        [9.9919e-01, 9.8068e-01, 8.5193e-01, 7.5177e-01, 3.0177e-01],
        [9.9903e-01, 9.8733e-01, 8.8082e-01, 7.1181e-01, 3.9153e-01],
        [9.9951e-01, 9.8788e-01, 8.6199e-01, 8.1476e-01, 1.9143e-01],
        [5.6593e-01, 3.1059e-01, 2.2761e-01, 5.0335e-02, 1.2734e-02],
        [9.7045e-01, 7.7929e-01, 4.7107e-01, 1.8879e-01, 4.9931e-02],
        [9.7391e-01, 7.8025e-01, 4.3663e-01, 1.8442e-01, 4.8424e-02],
        [9.2678e-01, 6.4574e-01, 2.5876e-01, 7.0642e-02, 1.1195e-02],
        [6.2562e-01, 3.6278e-01, 1.2997e-01, 2.9578e-02, 8.4060e-03],
        [6.2652e-01, 4.5306e-01, 1.4715e-01, 1.0266e-02, 2.5591e-03],
        [9.4489e-01,

Train progress: 100%|█████████████████████████| 4/4 [00:01<00:00,  3.86it/s, accuracy=70, loss=42.4]


Train Confusion matrix :
[[ 56  15   0   0   0   0]
 [191  14   0   0   0   0]
 [104   6   0   0   0   0]
 [142   3   0   0   0   0]
 [100   1   0   0   0   0]
 [ 48   0   0   0   0   0]]



[INFO] EPOCH: 3/5
Train loss: 104.347664, Train accuracy: 0.1029
Val loss: 255.796417, Val accuracy: 0.2975



Train progress:  50%|█████████████             | 2/4 [00:00<00:00,  3.26it/s, accuracy=34, loss=109]

tensor([[9.7156e-01, 7.5247e-01, 4.5169e-01, 2.2540e-01, 6.4127e-02],
        [1.5721e-01, 3.4984e-01, 5.5012e-02, 1.1056e-02, 7.0930e-04],
        [2.9331e-01, 4.3902e-01, 9.0008e-02, 2.3411e-02, 1.6412e-03],
        [9.9959e-01, 9.8487e-01, 9.7178e-01, 7.7952e-01, 8.2900e-01],
        [6.0831e-01, 4.4354e-01, 1.0871e-01, 2.3895e-02, 2.8654e-03],
        [9.6399e-01, 7.4110e-01, 5.7886e-01, 2.5756e-01, 5.7919e-02],
        [9.9803e-01, 9.6382e-01, 8.3893e-01, 3.5811e-01, 2.8030e-01],
        [9.8964e-01, 8.5746e-01, 7.4282e-01, 3.2565e-01, 2.1174e-01],
        [9.6659e-01, 7.5420e-01, 3.5061e-01, 8.4696e-02, 1.8386e-02],
        [9.9624e-01, 9.2911e-01, 8.1760e-01, 3.6459e-01, 2.8316e-01],
        [9.6327e-01, 5.9301e-01, 3.5168e-01, 1.6568e-01, 3.3087e-02],
        [9.7116e-01, 8.2428e-01, 4.0386e-01, 9.1167e-02, 3.5618e-02],
        [9.9864e-01, 9.5708e-01, 9.2921e-01, 7.8359e-01, 7.3344e-01],
        [9.0861e-01, 6.8979e-01, 3.7220e-01, 8.2161e-02, 1.9369e-02],
        [2.5888e-01,

Train progress:  75%|██████████████████▊      | 3/4 [00:00<00:00,  4.59it/s, accuracy=63, loss=34.9]

tensor([[9.5997e-01, 7.3163e-01, 6.2334e-01, 2.0411e-01, 3.3866e-02],
        [9.4186e-01, 6.6192e-01, 5.7916e-01, 1.3696e-01, 2.8822e-02],
        [9.9329e-01, 9.0215e-01, 6.3692e-01, 1.9017e-01, 3.9990e-02],
        [9.1743e-01, 6.4124e-01, 1.6933e-01, 4.6196e-02, 6.1209e-03],
        [8.5577e-01, 5.0794e-01, 1.7206e-01, 4.2307e-02, 5.0637e-03],
        [9.5343e-01, 7.5174e-01, 6.5826e-01, 1.9782e-01, 6.1588e-02],
        [5.7631e-01, 3.0606e-01, 8.3344e-02, 2.1318e-02, 1.8320e-03],
        [9.9763e-01, 9.3135e-01, 8.5032e-01, 4.6009e-01, 1.8189e-01],
        [9.7450e-01, 6.5809e-01, 3.9369e-01, 2.2011e-01, 5.3446e-02],
        [8.1169e-01, 4.8246e-01, 1.5911e-01, 2.2595e-02, 3.1497e-03],
        [9.9916e-01, 9.7283e-01, 9.5514e-01, 8.0917e-01, 5.3331e-01],
        [4.5834e-01, 1.7901e-01, 1.1135e-01, 3.1585e-02, 4.9131e-03],
        [3.0716e-01, 1.7385e-01, 9.6071e-02, 2.6010e-02, 1.3760e-03],
        [9.7111e-01, 8.0873e-01, 5.1226e-01, 2.0110e-01, 5.0785e-02],
        [9.9311e-01,

Train progress: 100%|█████████████████████████| 4/4 [00:00<00:00,  4.01it/s, accuracy=63, loss=34.9]


Train Confusion matrix :
[[ 54  17   0   0   0   0]
 [196   9   0   0   0   0]
 [108   2   0   0   0   0]
 [142   3   0   0   0   0]
 [101   0   0   0   0   0]
 [ 48   0   0   0   0   0]]



[INFO] EPOCH: 4/5
Train loss: 82.513542, Train accuracy: 0.0926
Val loss: 159.731201, Val accuracy: 0.0992



Train progress:  50%|████████████▌            | 2/4 [00:00<00:00,  3.47it/s, accuracy=42, loss=72.6]

tensor([[9.9198e-01, 9.1607e-01, 6.0933e-01, 1.4662e-01, 1.5552e-02],
        [9.0344e-01, 6.1214e-01, 2.9462e-01, 1.2151e-01, 1.8017e-02],
        [9.9794e-01, 9.6360e-01, 9.8334e-01, 8.3666e-01, 4.0899e-01],
        [6.5428e-01, 1.9606e-01, 4.9540e-02, 1.7926e-02, 2.4634e-03],
        [9.0234e-01, 5.9340e-01, 1.5439e-01, 2.9201e-02, 2.2583e-03],
        [3.1660e-01, 7.8655e-02, 8.9602e-02, 1.7269e-02, 2.7547e-03],
        [7.7211e-01, 3.0659e-01, 8.4857e-02, 5.7395e-02, 1.0690e-02],
        [9.6103e-01, 7.2376e-01, 4.1763e-01, 1.4183e-01, 1.3534e-02],
        [9.7878e-01, 8.5377e-01, 7.0775e-01, 1.5659e-01, 1.4703e-02],
        [7.9877e-01, 3.4769e-01, 1.7598e-01, 6.0814e-02, 1.4568e-02],
        [9.8252e-01, 7.8367e-01, 7.6647e-01, 3.9410e-01, 8.0837e-02],
        [1.0808e-01, 3.8933e-02, 1.2152e-02, 3.3203e-03, 3.6777e-04],
        [2.7457e-01, 7.9343e-02, 3.8629e-02, 1.2891e-02, 1.8697e-03],
        [9.9824e-01, 9.6886e-01, 9.4815e-01, 5.6735e-01, 1.3133e-01],
        [4.9062e-01,

Train progress:  75%|██████████████████▊      | 3/4 [00:00<00:00,  4.81it/s, accuracy=71, loss=23.7]

tensor([[9.8121e-01, 7.4507e-01, 2.9139e-01, 2.2430e-01, 3.4491e-02],
        [7.7419e-01, 2.3539e-01, 1.1188e-01, 1.1418e-02, 1.0357e-03],
        [9.9487e-01, 9.3283e-01, 8.0046e-01, 6.0571e-01, 1.3854e-01],
        [9.9822e-01, 9.6892e-01, 9.5086e-01, 8.4916e-01, 2.4718e-01],
        [4.5940e-01, 8.0806e-02, 2.4281e-02, 1.5305e-02, 1.6384e-03],
        [9.8220e-01, 8.5933e-01, 6.2797e-01, 2.3208e-01, 3.3711e-02],
        [9.9429e-01, 8.5785e-01, 6.0992e-01, 5.8212e-01, 1.4418e-01],
        [9.9861e-01, 9.7788e-01, 9.2883e-01, 6.7043e-01, 1.1656e-01],
        [9.9913e-01, 9.7428e-01, 9.9115e-01, 9.9347e-01, 9.7495e-01],
        [9.9645e-01, 9.3101e-01, 7.1391e-01, 4.4203e-01, 9.9722e-02],
        [3.4357e-01, 5.0111e-02, 5.5546e-02, 2.1292e-02, 3.5499e-03],
        [8.6760e-01, 3.2722e-01, 1.4268e-01, 7.6328e-02, 1.1406e-02],
        [8.6531e-01, 3.5031e-01, 1.1098e-01, 4.8738e-02, 7.7900e-03],
        [5.6553e-01, 1.2748e-01, 4.3161e-02, 6.0843e-03, 8.2086e-04],
        [3.5980e-01,

Train progress: 100%|█████████████████████████| 4/4 [00:00<00:00,  4.21it/s, accuracy=71, loss=23.7]


Train Confusion matrix :
[[ 71   0   0   0   0   0]
 [205   0   0   0   0   0]
 [110   0   0   0   0   0]
 [145   0   0   0   0   0]
 [101   0   0   0   0   0]
 [ 48   0   0   0   0   0]]



[INFO] EPOCH: 5/5
Train loss: 64.181602, Train accuracy: 0.1044
Val loss: 100.911156, Val accuracy: 0.0992

[INFO] Network evaluation ...


Test progress: 100%|████████████████████████████████████████| 2/2 [00:00<00:00,  3.50it/s, loss=127]


Confusion matrix :
[[ 2 24  0  0  0  0]
 [ 3 58  0  0  0  0]
 [ 0 34  0  0  0  0]
 [ 0 39  0  0  0  0]
 [ 0 29  0  0  0  0]
 [ 0 12  0  0  0  0]]

MS: 0.0000

QWK: 0.0219

MAE: 1.3632

CCR: 0.2985

1-off: 0.6020

[INFO] Total training time: 8.83s
