## Importing libraries

In [1]:
import random

import numpy as np
import pandas as pd
import torch
from scipy.special import softmax
from sklearn.metrics import (
    accuracy_score,
    cohen_kappa_score,
    confusion_matrix,
    mean_absolute_error,
)
from skorch import NeuralNetClassifier
from skorch.callbacks import EarlyStopping, LRScheduler
from skorch.dataset import ValidSplit
from torch import cuda, nn
from torch.nn import CrossEntropyLoss
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torchvision import models
from torchvision.transforms import Compose, ToTensor

from dlordinal.datasets import FGNet
from dlordinal.losses import (
    BetaLoss,
    BinomialLoss,
    CORNLoss,
    EMDLoss,
    GeometricLoss,
    TriangularLoss,
    WKLoss,
)
from dlordinal.metrics import accuracy_off1, amae, mmae, ranked_probability_score
from dlordinal.output_layers import COPOC

## Dataset
Download `FGNet` dataset.

In [2]:
fgnet_train = FGNet(
    root="./datasets",
    download=True,
    train=True,
    transform=Compose([ToTensor()]),
)

fgnet_test = FGNet(
    root="./datasets",
    download=True,
    train=False,
    transform=Compose([ToTensor()]),
)

num_classes = len(fgnet_train.classes)
classes = fgnet_train.classes
targets = fgnet_train.targets

# Get CUDA device
device = "cuda" if cuda.is_available() else "cpu"
print(f"Using {device} device")

Files already downloaded and verified
Files already processed and verified
Files already split and verified
Files already downloaded and verified
Files already processed and verified
Files already split and verified
Using cuda device


## Metrics 
Metrics to evaluate different ordinal losses.

In [3]:
def is_unimodal(probs):
    """Check if a 1D array is unimodal (increases to a peak, then decreases)."""
    peak_idx = np.argmax(probs)
    # Increasing up to peak
    inc = np.all(np.diff(probs[: peak_idx + 1]) >= 0)
    # Decreasing after peak
    dec = np.all(np.diff(probs[peak_idx:]) <= 0)
    return inc and dec


def check_unimodality(y_pred):
    """Check unimodality for each row in y_pred and return the proportion."""
    unimodal_flags = np.array([is_unimodal(row) for row in y_pred])
    # Proportion of rows that are unimodal
    proportion = np.mean(unimodal_flags)
    print(
        f"Unimodal predictions: {np.sum(unimodal_flags)} / {len(y_pred)} ({proportion})"
    )
    return proportion


def calculate_metrics(y_true, y_pred):

    if np.allclose(np.sum(y_pred, axis=1), 1):
        y_pred_proba = y_pred
    else:
        y_pred_proba = softmax(y_pred, axis=1)

    y_pred_max = np.argmax(y_pred, axis=1)

    # Metrics
    amae_metric = amae(y_true, y_pred)
    mmae_metric = mmae(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred_max)
    acc = accuracy_score(y_true, y_pred_max)
    acc_1off = accuracy_off1(y_true, y_pred)
    qwk = cohen_kappa_score(y_true, y_pred_max, weights="quadratic")
    rps = ranked_probability_score(y_true, y_pred_proba)
    # Check unimodality
    unimodal_prop = check_unimodality(y_pred_proba)

    metrics = {
        "ACC": acc,
        "1OFF": acc_1off,
        "MAE": mae,
        "QWK": qwk,
        "AMAE": amae_metric,
        "MMAE": mmae_metric,
        "RPS": rps,
        "Unimodality": unimodal_prop,
    }

    for key, value in metrics.items():
        print(f"{key}: {value}")

    print(confusion_matrix(y_true, y_pred_max))

    return metrics

## Experiment
We want to do a brief comparison of several (ordinal) losses using `PyTorch` and `Skorch`
with ResNet18, a pre-trained convolutional neural network, as the model architecture. 
Concretely, we compare Cross Entropy (CE) Loss with several ordinal approaches from the dlordinal library:

- Cross Entropy (CE) Loss
- Squared Earth Mover's Distance (EMD) Loss [1]
- Weighted Kappa Loss [2]
- Binomial Cross Entropy Loss  [3]
- Triangular Cross Entropy Loss [4]
- Beta Cross Entropy Loss [5]
- Geometric Cross Entropy Loss [6]
- Conformal prediction sets for ordinal classification (COPOC) [7]

[1] Hou, L., Yu, C. P., & Samaras, D. (2016). Squared earth mover's distance-based loss for training deep neural networks. arXiv preprint arXiv:1611.05916. 

[2] de La Torre, J., Puig, D., & Valls, A. (2018). Weighted kappa loss function for multi-class classification of ordinal data in deep learning. Pattern Recognition Letters, 105, 144-154.

[3] Liu, X., Fan, F., Kong, L., Diao, Z., Xie, W., Lu, J., & You, J. (2020). Unimodal regularized neuron stick-breaking for ordinal classification. Neurocomputing, 388, 34-44.

[4] Vargas, V. M., Gutiérrez, P. A., Barbero-Gómez, J., & Hervás-Martínez, C. (2023). Soft labelling based on triangular distributions for ordinal classification. Information Fusion, 93, 258-267.

[5] Vargas, V. M., Gutiérrez, P. A., & Hervás-Martínez, C. (2022). Unimodal regularisation based on beta distribution for deep ordinal regression. Pattern Recognition, 122, 108310.

[6] Haas, S., & Hüllermeier, E. (2023, September). Rectifying bias in ordinal observational data using unimodal label smoothing. In Joint European Conference on Machine Learning and Knowledge Discovery in Databases (pp. 3-18). Cham: Springer Nature Switzerland.

[7] Dey, P., Merugu, S., & Kaveri, S. R. (2023). Conformal prediction sets for ordinal classification. Advances in Neural Information Processing Systems, 36, 879-899.



In [4]:
# Loss functions
losses = [
    CORNLoss(num_classes=num_classes).to(device),
    CrossEntropyLoss().to(device),
    COPOC().to(device),
    EMDLoss(num_classes=num_classes).to(device),
    WKLoss(num_classes=num_classes, use_logits=True).to(device),
    BinomialLoss(base_loss=nn.CrossEntropyLoss(), num_classes=num_classes).to(device),
    TriangularLoss(base_loss=nn.CrossEntropyLoss(), num_classes=num_classes).to(device),
    BetaLoss(base_loss=nn.CrossEntropyLoss(), num_classes=num_classes).to(device),
    GeometricLoss(
        base_loss=nn.CrossEntropyLoss(),
        num_classes=num_classes,
        alphas=[0.15, 0.35, 0.35, 0.35, 0.35, 0.15],
    ).to(device),
]

# Evaluate each loss K times with different seeds to obtain a more robust result
K = 3

result = pd.DataFrame()


def set_seed(seed):
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    # Add deterministic settings
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def label_from_logits(logits):
    """Converts logits to class labels.
    This function is specific to CORN.
    """
    probas = torch.sigmoid(logits)
    probas = torch.cumprod(probas, dim=1)
    predict_levels = probas > 0.5
    predicted_labels = torch.sum(predict_levels, dim=1)
    return predicted_labels


for loss_fn in losses:

    for k in range(K):
        # Make results reproducible
        seed = k
        set_seed(seed)  # Use K different seeds

        # Initialize ResNet18 model
        model = models.resnet18(weights="IMAGENET1K_V1")
        if type(loss_fn).__name__ == "COPOC":
            model.fc = nn.Sequential(
                nn.Linear(model.fc.in_features, num_classes), loss_fn
            )
            loss = CrossEntropyLoss().to(device)
        elif type(loss_fn).__name__ == "CORNLoss":
            model.fc = nn.Linear(model.fc.in_features, num_classes - 1)
            loss = loss_fn
        else:
            model.fc = nn.Linear(model.fc.in_features, num_classes)
            loss = loss_fn
        model.to(device)

        # Skorch estimator
        estimator = NeuralNetClassifier(
            module=model,
            criterion=loss,
            optimizer=Adam,
            lr=0.001,
            max_epochs=30,
            # verbose=0,
            train_split=ValidSplit(
                0.1, random_state=seed
            ),  # Use 10% of the data for validation
            callbacks=[
                EarlyStopping(patience=5, monitor="valid_loss"),
                LRScheduler(policy=ReduceLROnPlateau, patience=3, factor=0.5),
            ],
            device=device,
            batch_size=200,
        )

        print("#" + str(k) + " " + type(loss_fn).__name__)

        estimator.fit(
            X=fgnet_train, y=torch.tensor(fgnet_train.targets, dtype=torch.long)
        )

        test_probs = estimator.predict_proba(fgnet_test)

        if type(loss_fn).__name__ == "CORNLoss":
            test_logits = estimator.forward(fgnet_test)
            test_labels = label_from_logits(torch.tensor(test_logits))
            test_probs = np.zeros((len(test_labels), num_classes))
            test_probs[np.arange(len(test_labels)), test_labels.numpy()] = 1.0

        metrics = calculate_metrics(np.array(fgnet_test.targets), test_probs)
        print("\n")

        df = pd.DataFrame([metrics])
        df["iteration"] = k
        df["loss"] = type(loss_fn).__name__

        result = pd.concat([result, df], ignore_index=True)

#0 CORNLoss
  epoch    train_loss    valid_acc    valid_loss      lr      dur
-------  ------------  -----------  ------------  ------  -------
      1        0.5653       0.0617        0.4744  0.0010  13.9898
      2        0.2470       0.1235        0.5040  0.0010  3.9989
      3        0.1119       0.1728        0.5354  0.0010  3.1230
      4        0.0460       0.0741        0.6443  0.0010  3.3989
      5        0.0203       0.0864        0.6501  0.0010  3.1441
Stopping since valid_loss has not improved in the last 5 epochs.


/tmp/ipykernel_3700307/1850142562.py:96: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_labels = label_from_logits(torch.tensor(test_logits))


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.4427860696517413
1OFF: 0.8805970149253731
MAE: 0.7014925373134329
QWK: 0.7337680856322604
AMAE: 0.7617965367965368
MMAE: 1.6428571428571428
RPS: 0.7014925373134329
Unimodality: 1.0
[[20  2  0  0  0  0]
 [16 17 19  8  0  0]
 [ 3  6  8 14  1  1]
 [ 2  0  2 37  1  0]
 [ 0  0  0 24  5  1]
 [ 0  0  2  7  3  2]]


#1 CORNLoss
  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.5086       0.0988        0.7149  0.0010  4.8940
      2        0.2538       0.2346        1.7509  0.0010  5.5896
      3        0.1114       0.1728        0.8644  0.0010  4.1151
      4        0.0410       0.0988        0.5378  0.0010  3.6191
      5        0.0114       0.1358        0.6562  0.0010  4.3532
      6        0.0045       0.0988        0.6954  0.0010  4.2179
      7        0.0025       0.0741        0.6239  0.0010  4.8488
      8        0.0017       0.0494        0.5833

/tmp/ipykernel_3700307/1850142562.py:96: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_labels = label_from_logits(torch.tensor(test_logits))


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5223880597014925
1OFF: 0.8805970149253731
MAE: 0.6169154228855721
QWK: 0.7549797696856521
AMAE: 0.7035714285714286
MMAE: 1.5
RPS: 0.6169154228855721
Unimodality: 1.0
[[15  6  0  1  0  0]
 [ 8 34  7  9  2  0]
 [ 0  8  9 15  1  0]
 [ 0  2  2 34  4  0]
 [ 0  0  2 14 12  2]
 [ 0  0  1  6  6  1]]


#2 CORNLoss
  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.5608       0.0370        0.4806  0.0010  4.6101
      2        0.2390       0.1605        0.5362  0.0010  4.1834
      3        0.1169       0.0370        0.5462  0.0010  5.2815
      4        0.0474       0.0988        0.5037  0.0010  4.5763
      5        0.0202       0.0988        0.5239  0.0010  3.6349
Stopping since valid_loss has not improved in the last 5 epochs.


/tmp/ipykernel_3700307/1850142562.py:96: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_labels = label_from_logits(torch.tensor(test_logits))


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5472636815920398
1OFF: 0.8905472636815921
MAE: 0.5920398009950248
QWK: 0.7658021441473655
AMAE: 0.6843434343434344
MMAE: 1.5
RPS: 0.5920398009950248
Unimodality: 1.0
[[17  5  0  0  0  0]
 [ 7 41  7  3  2  0]
 [ 1 15  6 10  1  0]
 [ 0  6  4 28  3  1]
 [ 0  0  1 14 14  1]
 [ 0  1  2  4  3  4]]


#0 CrossEntropyLoss
  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.7123       0.3333        1.8125  0.0010  4.2837
      2        0.7194       0.4074        1.9652  0.0010  2.9990
      3        0.1908       0.5185        1.6160  0.0010  2.9737
      4        0.0565       0.4691        1.6016  0.0010  3.3110
      5        0.0140       0.5062        1.6081  0.0010  3.7191
      6        0.0059       0.5185        1.6873  0.0010  3.0958
      7        0.0024       0.5679        1.7967  0.0010  3.2917
      8        0.0020       0.5679        1.7081  0.001

## Result
Displays the mean results for each loss over the K iterations.

In [5]:
result.set_index(["loss", "iteration"], inplace=True)
result.groupby("loss").agg("mean").style.highlight_max(
    axis=0, subset=["ACC", "1OFF", "QWK"], color="green"
).highlight_min(axis=0, subset=["MAE", "AMAE", "MMAE", "RPS"], color="green")