## Importing libraries

In [1]:
import random

import numpy as np
import pandas as pd
import torch
from scipy.special import softmax
from sklearn.metrics import (
    accuracy_score,
    cohen_kappa_score,
    confusion_matrix,
    mean_absolute_error,
)
from skorch import NeuralNetClassifier
from skorch.callbacks import EarlyStopping, LRScheduler
from skorch.dataset import ValidSplit
from torch import cuda, nn
from torch.nn import CrossEntropyLoss
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torchvision import models
from torchvision.transforms import Compose, ToTensor

from dlordinal.datasets import FGNet
from dlordinal.losses import (
    BetaLoss,
    BinomialLoss,
    CORNLoss,
    EMDLoss,
    GeometricLoss,
    SLACELoss,
    SORDLoss,
    TriangularLoss,
    WKLoss,
)
from dlordinal.metrics import accuracy_off1, amae, mmae, ranked_probability_score
from dlordinal.output_layers import COPOC
from dlordinal.wrappers import CORNClassifierWrapper

## Dataset
Download `FGNet` dataset.

In [2]:
fgnet_train = FGNet(
    root="./datasets",
    download=True,
    train=True,
    transform=Compose([ToTensor()]),
)

fgnet_test = FGNet(
    root="./datasets",
    download=True,
    train=False,
    transform=Compose([ToTensor()]),
)

num_classes = len(fgnet_train.classes)
classes = fgnet_train.classes
targets = fgnet_train.targets

# Get CUDA device
device = "cuda" if cuda.is_available() else "cpu"
print(f"Using {device} device")

Files already downloaded and verified
Files already processed and verified
Files already split and verified
Files already downloaded and verified
Files already processed and verified
Files already split and verified
Using cuda device


## Metrics 
Metrics to evaluate different ordinal losses.

In [3]:
def is_unimodal(probs):
    """Check if a 1D array is unimodal (increases to a peak, then decreases)."""
    peak_idx = np.argmax(probs)
    # Increasing up to peak
    inc = np.all(np.diff(probs[: peak_idx + 1]) >= 0)
    # Decreasing after peak
    dec = np.all(np.diff(probs[peak_idx:]) <= 0)
    return inc and dec


def check_unimodality(y_pred):
    """Check unimodality for each row in y_pred and return the proportion."""
    unimodal_flags = np.array([is_unimodal(row) for row in y_pred])
    # Proportion of rows that are unimodal
    proportion = np.mean(unimodal_flags)
    print(
        f"Unimodal predictions: {np.sum(unimodal_flags)} / {len(y_pred)} ({proportion})"
    )
    return proportion


def calculate_metrics(y_true, y_pred):

    if np.allclose(np.sum(y_pred, axis=1), 1):
        y_pred_proba = y_pred
    else:
        y_pred_proba = softmax(y_pred, axis=1)

    y_pred_max = np.argmax(y_pred, axis=1)

    # Metrics
    amae_metric = amae(y_true, y_pred)
    mmae_metric = mmae(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred_max)
    acc = accuracy_score(y_true, y_pred_max)
    acc_1off = accuracy_off1(y_true, y_pred)
    qwk = cohen_kappa_score(y_true, y_pred_max, weights="quadratic")
    rps = ranked_probability_score(y_true, y_pred_proba)
    # Check unimodality
    unimodal_prop = check_unimodality(y_pred_proba)

    metrics = {
        "ACC": acc,
        "1OFF": acc_1off,
        "MAE": mae,
        "QWK": qwk,
        "AMAE": amae_metric,
        "MMAE": mmae_metric,
        "RPS": rps,
        "Unimodality": unimodal_prop,
    }

    for key, value in metrics.items():
        print(f"{key}: {value}")

    print(confusion_matrix(y_true, y_pred_max))

    return metrics

## Experiment
We want to do a brief comparison of several (ordinal) losses using `PyTorch` and `Skorch`
with ResNet18, a pre-trained convolutional neural network, as the model architecture. 
Concretely, we compare Cross Entropy (CE) Loss with several ordinal approaches from the dlordinal library:

- Cross Entropy (CE) Loss
- Squared Earth Mover's Distance (EMD) Loss [1]
- Weighted Kappa Loss [2]
- Binomial Cross Entropy Loss  [3]
- Triangular Cross Entropy Loss [4]
- Beta Cross Entropy Loss [5]
- Geometric Cross Entropy Loss [6]
- Conformal prediction sets for ordinal classification (COPOC) [7]

[1] Hou, L., Yu, C. P., & Samaras, D. (2016). Squared earth mover's distance-based loss for training deep neural networks. arXiv preprint arXiv:1611.05916. 

[2] de La Torre, J., Puig, D., & Valls, A. (2018). Weighted kappa loss function for multi-class classification of ordinal data in deep learning. Pattern Recognition Letters, 105, 144-154.

[3] Liu, X., Fan, F., Kong, L., Diao, Z., Xie, W., Lu, J., & You, J. (2020). Unimodal regularized neuron stick-breaking for ordinal classification. Neurocomputing, 388, 34-44.

[4] Vargas, V. M., Gutiérrez, P. A., Barbero-Gómez, J., & Hervás-Martínez, C. (2023). Soft labelling based on triangular distributions for ordinal classification. Information Fusion, 93, 258-267.

[5] Vargas, V. M., Gutiérrez, P. A., & Hervás-Martínez, C. (2022). Unimodal regularisation based on beta distribution for deep ordinal regression. Pattern Recognition, 122, 108310.

[6] Haas, S., & Hüllermeier, E. (2023, September). Rectifying bias in ordinal observational data using unimodal label smoothing. In Joint European Conference on Machine Learning and Knowledge Discovery in Databases (pp. 3-18). Cham: Springer Nature Switzerland.

[7] Dey, P., Merugu, S., & Kaveri, S. R. (2023). Conformal prediction sets for ordinal classification. Advances in Neural Information Processing Systems, 36, 879-899.



In [4]:
# Loss functions
losses = [
    SORDLoss(
        alpha=1.0,
        num_classes=num_classes,
        train_targets=fgnet_train.targets,
        use_logits=True,
    ).to(device),
    SLACELoss(alpha=1.0, num_classes=num_classes, use_logits=True).to(device),
    CORNLoss(num_classes=num_classes).to(device),
    CrossEntropyLoss().to(device),
    COPOC().to(device),
    EMDLoss(num_classes=num_classes).to(device),
    WKLoss(num_classes=num_classes, use_logits=True).to(device),
    BinomialLoss(base_loss=nn.CrossEntropyLoss(), num_classes=num_classes).to(device),
    TriangularLoss(base_loss=nn.CrossEntropyLoss(), num_classes=num_classes).to(device),
    BetaLoss(base_loss=nn.CrossEntropyLoss(), num_classes=num_classes).to(device),
    GeometricLoss(
        base_loss=nn.CrossEntropyLoss(),
        num_classes=num_classes,
        alphas=[0.15, 0.35, 0.35, 0.35, 0.35, 0.15],
    ).to(device),
]

# Evaluate each loss K times with different seeds to obtain a more robust result
K = 3

result = pd.DataFrame()


def set_seed(seed):
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    # Add deterministic settings
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


for loss_fn in losses:

    for k in range(K):
        # Make results reproducible
        seed = k
        set_seed(seed)  # Use K different seeds

        # Initialize ResNet18 model
        model = models.resnet18(weights="IMAGENET1K_V1")
        if type(loss_fn).__name__ == "COPOC":
            model.fc = nn.Sequential(
                nn.Linear(model.fc.in_features, num_classes), loss_fn
            )
            loss = CrossEntropyLoss().to(device)
        elif type(loss_fn).__name__ == "CORNLoss":
            model.fc = nn.Linear(model.fc.in_features, num_classes - 1)
            loss = loss_fn
        else:
            model.fc = nn.Linear(model.fc.in_features, num_classes)
            loss = loss_fn
        model.to(device)

        # Skorch estimator
        estimator = NeuralNetClassifier(
            module=model,
            criterion=loss,
            optimizer=Adam,
            lr=0.001,
            max_epochs=30,
            # verbose=0,
            train_split=ValidSplit(
                0.1, random_state=seed
            ),  # Use 10% of the data for validation
            callbacks=[
                EarlyStopping(patience=5, monitor="valid_loss"),
                LRScheduler(policy=ReduceLROnPlateau, patience=3, factor=0.5),
            ],
            device=device,
            batch_size=200,
        )

        if type(loss_fn).__name__ == "CORNLoss":
            estimator = CORNClassifierWrapper(estimator)

        print("#" + str(k) + " " + type(loss_fn).__name__)

        estimator.fit(
            X=fgnet_train, y=torch.tensor(fgnet_train.targets, dtype=torch.long)
        )

        test_probs = estimator.predict_proba(fgnet_test)

        metrics = calculate_metrics(np.array(fgnet_test.targets), test_probs)
        print("\n")

        df = pd.DataFrame([metrics])
        df["iteration"] = k
        df["loss"] = type(loss_fn).__name__

        result = pd.concat([result, df], ignore_index=True)

#0 SORDLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.8457       0.1358        2.2935  0.0010  2.3263


      2        1.5996       0.2469        1.8476  0.0010  1.1625


      3        1.4552       0.2593        1.9090  0.0010  0.9652


      4        1.3808       0.3580        1.5886  0.0010  1.1055


      5        1.3432       0.4198        1.5440  0.0010  1.2633


      6        1.3197       0.4691        1.5687  0.0010  1.1341


      7        1.3115       0.5185        1.5293  0.0010  1.2788


      8        1.3036       0.5309        1.5108  0.0010  1.1190


      9        1.3002       0.5309        1.4948  0.0010  1.3823


     10        1.2976       0.5432        1.4911  0.0010  1.1718


     11        1.2960       0.5802        1.4808  0.0010  1.1353


     12        1.2951       0.5802        1.4831  0.0010  1.1941


     13        1.2946       0.5926        1.4715  0.0010  1.0635


     14        1.2941       0.5679        1.4731  0.0010  1.0104


     15        1.2939       0.5679        1.4755  0.0010  1.0653


     16        1.2937       0.5556        1.4748  0.0010  1.0909


     17        1.2936       0.5432        1.4771  0.0010  1.0560


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 199 / 201 (0.9900497512437811)
ACC: 0.6417910447761194
1OFF: 0.9751243781094527
MAE: 0.38308457711442784
QWK: 0.8913925135549745
AMAE: 0.430952380952381
MMAE: 0.7272727272727273
RPS: 0.35862240964366643
Unimodality: 0.9900497512437811
[[16  6  0  0  0  0]
 [ 1 50  7  2  0  0]
 [ 1 13 10  9  0  0]
 [ 0  0 10 29  3  0]
 [ 0  0  1  9 18  2]
 [ 0  0  0  1  7  6]]




#1 SORDLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.8638       0.2840        1.7744  0.0010  1.3147


      2        1.5728       0.2346        1.9904  0.0010  1.1012


      3        1.4369       0.3210        1.8427  0.0010  1.0353


      4        1.3803       0.2469        1.8792  0.0010  1.2077


      5        1.3413       0.3704        1.6867  0.0010  1.0365


      6        1.3240       0.4074        1.5905  0.0010  1.0732


      7        1.3108       0.5556        1.5253  0.0010  1.0902


      8        1.3048       0.5062        1.5314  0.0010  1.1737


      9        1.3002       0.5926        1.4991  0.0010  1.1147


     10        1.2977       0.6790        1.4787  0.0010  1.1578


     11        1.2955       0.6049        1.4799  0.0010  1.1065


     12        1.2946       0.6543        1.4758  0.0010  1.1420


     13        1.2937       0.6173        1.4790  0.0010  1.1126


     14        1.2934       0.6543        1.4723  0.0010  1.1567


     15        1.2928       0.6049        1.4761  0.0010  1.0727


     16        1.2926       0.6173        1.4729  0.0010  1.3642


     17        1.2924       0.5926        1.4751  0.0010  1.1029


     18        1.2923       0.6049        1.4740  0.0010  1.1817


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 199 / 201 (0.9900497512437811)
ACC: 0.6268656716417911
1OFF: 0.9701492537313433
MAE: 0.4079601990049751
QWK: 0.8790182903610166
AMAE: 0.4651154401154401
MMAE: 0.9285714285714286
RPS: 0.3578054218206612
Unimodality: 0.9900497512437811
[[18  4  0  0  0  0]
 [ 6 45  7  2  0  0]
 [ 0 11 10 12  0  0]
 [ 0  2  8 30  2  0]
 [ 0  0  0  9 19  2]
 [ 0  0  1  1  8  4]]




#2 SORDLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.9064       0.2346        2.3314  0.0010  1.1057


      2        1.5935       0.1728        2.1299  0.0010  1.0826


      3        1.4716       0.2840        2.0373  0.0010  1.2533


      4        1.3921       0.3086        1.7328  0.0010  1.2600


      5        1.3571       0.4074        1.6591  0.0010  1.1824


      6        1.3262       0.4691        1.5780  0.0010  1.2131


      7        1.3120       0.5062        1.5570  0.0010  1.1932


      8        1.3045       0.5062        1.5380  0.0010  1.1785


      9        1.3006       0.5679        1.5188  0.0010  1.0497


     10        1.2982       0.5556        1.5234  0.0010  1.1055


     11        1.2965       0.5432        1.5159  0.0010  1.0552


     12        1.2956       0.5309        1.5253  0.0010  1.0114


     13        1.2949       0.5679        1.5123  0.0010  1.2335


     14        1.2945       0.5679        1.5136  0.0010  1.0100


     15        1.2941       0.5556        1.5155  0.0010  1.0142


     16        1.2938       0.5432        1.5140  0.0010  0.9942


     17        1.2937       0.5556        1.5136  0.0010  1.1365


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.6069651741293532
1OFF: 0.9552238805970149
MAE: 0.4577114427860697
QWK: 0.8382293762575452
AMAE: 0.528030303030303
MMAE: 1.1428571428571428
RPS: 0.38302726179726654
Unimodality: 1.0
[[20  2  0  0  0  0]
 [ 3 45  9  2  1  0]
 [ 0  9 10 13  1  0]
 [ 0  0 13 27  2  0]
 [ 0  1  1  9 17  2]
 [ 0  1  0  2  8  3]]




#0 SLACELoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.0342       0.4444        1.0191  0.0010  1.2826


      2        0.4441       0.4691        1.2850  0.0010  1.1705


      3        0.2105       0.4074        1.7896  0.0010  1.1797


      4        0.0842       0.5556        0.8761  0.0010  1.0123


      5        0.0177       0.5185        1.1260  0.0010  1.0850


      6        0.0057       0.4815        1.3743  0.0010  1.0921


      7        0.0024       0.4815        1.4851  0.0010  1.1716


      8        0.0012       0.4815        1.4682  0.0010  1.0744


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 114 / 201 (0.5671641791044776)
ACC: 0.5422885572139303
1OFF: 0.9104477611940298
MAE: 0.5870646766169154
QWK: 0.7523527407135555
AMAE: 0.7374458874458875
MMAE: 1.6428571428571428
RPS: 0.4990800507929681
Unimodality: 0.5671641791044776
[[16  6  0  0  0  0]
 [ 2 52  4  2  0  0]
 [ 0 22  3  8  0  0]
 [ 0  2 15 23  2  0]
 [ 0  3  4 10 12  1]
 [ 0  1  3  3  4  3]]




#1 SLACELoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.0394       0.2963        3.0230  0.0010  1.1768


      2        0.5296       0.3704        1.4199  0.0010  1.1020


      3        0.2246       0.2963        1.7970  0.0010  1.0163


      4        0.0692       0.4691        1.2804  0.0010  1.2550


      5        0.0183       0.4444        1.4442  0.0010  1.0485


      6        0.0058       0.4568        1.4834  0.0010  1.1654


      7        0.0021       0.4568        1.4543  0.0010  1.1725


      8        0.0012       0.4691        1.4199  0.0010  1.3006


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 92 / 201 (0.4577114427860697)
ACC: 0.6169154228855721
1OFF: 0.9502487562189055
MAE: 0.43781094527363185
QWK: 0.8615293770298199
AMAE: 0.4566378066378067
MMAE: 0.6428571428571429
RPS: 0.3735753673188038
Unimodality: 0.4577114427860697
[[20  2  0  0  0  0]
 [ 3 46  8  2  1  0]
 [ 0 10 14  8  1  0]
 [ 0  2 13 23  4  0]
 [ 0  0  3 10 15  2]
 [ 0  0  0  1  7  6]]




#2 SLACELoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.0468       0.3210        3.0648  0.0010  1.0066


      2        0.5095       0.3704        1.9326  0.0010  1.3397


      3        0.1851       0.4198        1.6245  0.0010  1.1178


      4        0.0575       0.4198        1.5590  0.0010  1.1412


      5        0.0239       0.3951        1.3417  0.0010  1.3689


      6        0.0103       0.4938        1.5132  0.0010  1.2265


      7        0.0027       0.5432        1.5083  0.0010  1.1031


      8        0.0019       0.5432        1.3431  0.0010  1.0297


      9        0.0010       0.5556        1.1924  0.0010  1.0039


     10        0.0006       0.5679        1.0986  0.0010  1.0526


     11        0.0005       0.5679        1.0523  0.0010  1.0218


     12        0.0003       0.5802        1.0379  0.0010  1.2530


     13        0.0003       0.5802        1.0370  0.0010  1.1195


     14        0.0002       0.5802        1.0389  0.0010  1.0860


     15        0.0002       0.5679        1.0429  0.0010  1.1470


     16        0.0002       0.5679        1.0450  0.0010  1.0003


     17        0.0002       0.5679        1.0465  0.0010  1.0559


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 75 / 201 (0.373134328358209)
ACC: 0.5870646766169154
1OFF: 0.9253731343283582
MAE: 0.5074626865671642
QWK: 0.8226136684552386
AMAE: 0.549963924963925
MMAE: 0.9285714285714286
RPS: 0.41865390940515534
Unimodality: 0.373134328358209
[[21  1  0  0  0  0]
 [ 6 44  7  3  0  0]
 [ 0 16  5 10  2  0]
 [ 0  4 10 25  3  0]
 [ 0  1  2  8 16  3]
 [ 0  1  1  1  4  7]]




#0 CORNLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.5513       0.1235        1.0406  0.0010  1.4295


      2        0.2560       0.0494        0.6266  0.0010  1.1015


      3        0.1319       0.0617        0.5633  0.0010  1.1633


      4        0.0504       0.0864        0.6159  0.0010  1.2188


      5        0.0223       0.0864        0.5602  0.0010  1.1235


      6        0.0078       0.1358        0.5702  0.0010  1.1591


      7        0.0043       0.1235        0.6503  0.0010  1.0753


      8        0.0024       0.1235        0.7064  0.0010  1.0120


      9        0.0016       0.0864        0.7165  0.0010  1.1463


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5422885572139303
1OFF: 0.9353233830845771
MAE: 0.5422885572139303
QWK: 0.8002208724461624
AMAE: 0.6103896103896104
MMAE: 1.1428571428571428
RPS: 0.5422885572139303
Unimodality: 1.0
[[18  4  0  0  0  0]
 [ 2 40 12  6  0  0]
 [ 0 15  3 15  0  0]
 [ 0  1  7 32  2  0]
 [ 0  2  1 13 13  1]
 [ 0  1  0  2  8  3]]




#1 CORNLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.5260       0.1728        0.9998  0.0010  1.2800


      2        0.2281       0.1111        0.6686  0.0010  1.1093


      3        0.0985       0.0370        0.7282  0.0010  1.0722


      4        0.0443       0.1235        0.6845  0.0010  1.0628


      5        0.0183       0.1358        0.9289  0.0010  1.1727


      6        0.0104       0.0864        0.7248  0.0010  1.1785


      7        0.0035       0.1111        0.6657  0.0010  1.1442


      8        0.0023       0.0988        0.6877  0.0010  1.2651


      9        0.0015       0.0864        0.6913  0.0010  1.0954


     10        0.0010       0.0864        0.6774  0.0010  1.1809


     11        0.0008       0.0864        0.6600  0.0010  1.0970


     12        0.0006       0.0864        0.6473  0.0010  1.0604


     13        0.0005       0.0864        0.6370  0.0010  1.3160


     14        0.0005       0.0864        0.6292  0.0010  1.1314


     15        0.0004       0.0864        0.6248  0.0010  1.1705


     16        0.0004       0.0864        0.6225  0.0010  1.1756


     17        0.0003       0.0864        0.6214  0.0010  1.2273


     18        0.0003       0.0864        0.6208  0.0010  1.0130


     19        0.0003       0.0864        0.6204  0.0010  1.0728


     20        0.0003       0.0864        0.6205  0.0010  1.2408


     21        0.0003       0.0864        0.6206  0.0010  1.2587


     22        0.0003       0.0864        0.6210  0.0010  1.2900


     23        0.0002       0.0864        0.6216  0.0010  1.2740


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.6666666666666666
1OFF: 0.9651741293532339
MAE: 0.373134328358209
QWK: 0.8926892275897701
AMAE: 0.3847763347763348
MMAE: 0.9393939393939394
RPS: 0.373134328358209
Unimodality: 1.0
[[21  1  0  0  0  0]
 [ 2 54  1  2  1  0]
 [ 0 19  2 12  0  0]
 [ 0  2  6 30  4  0]
 [ 0  0  2  7 18  3]
 [ 0  0  0  0  5  9]]




#2 CORNLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.5872       0.0617        1.2498  0.0010  1.1012


      2        0.2619       0.0741        0.9058  0.0010  1.0354


      3        0.1025       0.1481        0.8964  0.0010  1.2488


      4        0.0456       0.0494        0.7768  0.0010  1.1610


      5        0.0213       0.0247        0.5853  0.0010  1.1819


      6        0.0090       0.0494        0.6324  0.0010  1.3149


      7        0.0040       0.0370        0.6845  0.0010  1.0998


      8        0.0028       0.0494        0.6414  0.0010  1.1411


      9        0.0016       0.0494        0.6069  0.0010  0.9900


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5920398009950248
1OFF: 0.9253731343283582
MAE: 0.5124378109452736
QWK: 0.8109326470849233
AMAE: 0.5871572871572872
MMAE: 1.2142857142857142
RPS: 0.5124378109452736
Unimodality: 1.0
[[22  0  0  0  0  0]
 [ 5 51  2  1  1  0]
 [ 0 18  8  5  2  0]
 [ 0  5 13 18  6  0]
 [ 0  2  1  8 17  2]
 [ 0  1  1  1  8  3]]




#0 CrossEntropyLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.6804       0.3580        1.9462  0.0010  1.2926


      2        0.7348       0.4444        1.4320  0.0010  1.2549


      3        0.2988       0.4568        2.2478  0.0010  1.2579


      4        0.0881       0.4691        2.1871  0.0010  1.2655


      5        0.0314       0.4444        2.8472  0.0010  1.0567


      6        0.0081       0.3951        3.1412  0.0010  1.0498


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 58 / 201 (0.2885572139303483)
ACC: 0.48258706467661694
1OFF: 0.835820895522388
MAE: 0.7661691542288557
QWK: 0.6069290839180244
AMAE: 0.96002886002886
MMAE: 2.0
RPS: 0.6487250902513457
Unimodality: 0.2885572139303483
[[14  8  0  0  0  0]
 [ 0 58  2  0  0  0]
 [ 0 26  3  3  1  0]
 [ 0 15 10 14  3  0]
 [ 0  7  4 13  6  0]
 [ 0  4  2  0  6  2]]




#1 CrossEntropyLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.6459       0.2716        4.1044  0.0010  1.0494


      2        0.8443       0.4074        1.6029  0.0010  1.0326


      3        0.3458       0.2593        2.5642  0.0010  1.1033


      4        0.1090       0.3827        2.0517  0.0010  1.1182


      5        0.0362       0.2963        2.9029  0.0010  1.0143


      6        0.0141       0.3210        3.4157  0.0010  1.0375


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 46 / 201 (0.22885572139303484)
ACC: 0.46766169154228854
1OFF: 0.8159203980099502
MAE: 0.7810945273631841
QWK: 0.6252138532021915
AMAE: 0.9289682539682541
MMAE: 2.2142857142857144
RPS: 0.6216194780626373
Unimodality: 0.22885572139303484
[[20  2  0  0  0  0]
 [ 5 43 12  0  0  0]
 [ 0 19 14  0  0  0]
 [ 0 17 19  4  2  0]
 [ 0  1 11  5 10  3]
 [ 0  4  4  0  3  3]]




#2 CrossEntropyLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.6442       0.3457        3.1197  0.0010  1.0072


      2        0.8247       0.3580        2.4673  0.0010  1.1084


      3        0.2777       0.2840        2.7142  0.0010  1.1358


      4        0.0830       0.3704        3.3355  0.0010  1.1711


      5        0.0225       0.3580        3.6315  0.0010  1.0323


      6        0.0062       0.4074        3.4631  0.0010  1.0118


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 103 / 201 (0.5124378109452736)
ACC: 0.43781094527363185
1OFF: 0.8756218905472637
MAE: 0.6965174129353234
QWK: 0.7096858906088149
AMAE: 0.7712121212121211
MMAE: 1.5714285714285714
RPS: 0.572435707554204
Unimodality: 0.5124378109452736
[[20  2  0  0  0  0]
 [ 4 25 26  5  0  0]
 [ 0  5 13 14  1  0]
 [ 0  1 15 25  1  0]
 [ 0  1  8 18  3  0]
 [ 0  0  1  8  3  2]]




#0 COPOC


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        2.0412       0.1605        4.3970  0.0010  1.0942


      2        1.7089       0.1481        7.5617  0.0010  1.0399


      3        1.5227       0.1852        3.7597  0.0010  1.1150


      4        1.4290       0.2099        2.2782  0.0010  1.1699


      5        1.2448       0.1481        2.8635  0.0010  1.0905


      6        1.1441       0.2593        2.0457  0.0010  1.0373


      7        1.0146       0.2716        1.5792  0.0010  1.1158


      8        0.9089       0.3457        1.3422  0.0010  1.1068


      9        0.8036       0.3210        1.5521  0.0010  1.1426


     10        0.6967       0.4198        1.2766  0.0010  1.2130


     11        0.6154       0.4198        1.3624  0.0010  1.1060


     12        0.5569       0.5062        1.3001  0.0010  1.1858


     13        0.5222       0.4074        1.4128  0.0010  1.0418


     14        0.5207       0.4815        1.4530  0.0010  1.0085


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.4626865671641791
1OFF: 0.9402985074626866
MAE: 0.6119402985074627
QWK: 0.8390472448385797
AMAE: 0.5465007215007215
MMAE: 0.8787878787878788
RPS: 0.4426715679432075
Unimodality: 1.0
[[21  1  0  0  0  0]
 [27 20  9  2  1  1]
 [ 1  6  9 13  4  0]
 [ 0  1 10 16 14  1]
 [ 0  0  0  3 20  7]
 [ 0  0  0  1  6  7]]




#1 COPOC


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        2.1268       0.1358        2.3919  0.0010  1.0529


      2        1.7602       0.1481        5.7732  0.0010  1.2719


      3        1.7023       0.1975        4.2121  0.0010  1.1960


      4        1.6054       0.3827        3.2208  0.0010  1.1514


      5        1.3249       0.3210        2.6071  0.0010  1.1306


      6        1.1791       0.3086        1.5378  0.0010  1.2001


      7        1.0005       0.2346        3.5332  0.0010  1.0258


      8        0.8165       0.3086        2.3909  0.0010  1.1002


      9        0.6830       0.4938        1.4263  0.0010  1.2020


     10        0.5964       0.4568        1.4452  0.0010  1.1502


     11        0.4930       0.3827        1.7600  0.0010  1.1369


     12        0.4059       0.4321        1.5156  0.0010  1.0338


     13        0.2919       0.5556        1.5291  0.0010  0.9935


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5671641791044776
1OFF: 0.945273631840796
MAE: 0.48756218905472637
QWK: 0.848959246549608
AMAE: 0.5420274170274171
MMAE: 0.9285714285714286
RPS: 0.38143956789646544
Unimodality: 1.0
[[15  7  0  0  0  0]
 [ 0 45 13  2  0  0]
 [ 0  9 14  8  2  0]
 [ 0  1 11 18 11  1]
 [ 0  0  2  8 18  2]
 [ 0  0  0  3  7  4]]




#2 COPOC


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.8867       0.1481        4.1355  0.0010  1.1850


      2        1.6592       0.2346        1.8803  0.0010  1.2170


      3        1.4429       0.1358        2.3432  0.0010  1.1753


      4        1.2024       0.1975        2.2340  0.0010  1.2333


      5        1.0639       0.3580        1.6483  0.0010  1.0642


      6        0.8864       0.3827        1.9821  0.0010  1.0482


      7        0.7324       0.4198        1.5914  0.0010  1.1123


      8        0.5825       0.4074        1.6348  0.0010  1.1298


      9        0.4911       0.3827        1.5896  0.0010  1.1720


     10        0.4380       0.4074        1.6600  0.0010  1.1706


     11        0.3820       0.4444        1.6040  0.0010  1.0171


     12        0.3310       0.3704        1.7734  0.0010  0.9907


     13        0.2465       0.4198        1.8193  0.0010  0.9959


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5920398009950248
1OFF: 0.9402985074626866
MAE: 0.47761194029850745
QWK: 0.8422253293104717
AMAE: 0.5281385281385281
MMAE: 1.0
RPS: 0.38111491644525847
Unimodality: 1.0
[[18  4  0  0  0  0]
 [ 1 40 16  2  1  0]
 [ 0 10 15  6  2  0]
 [ 0  0 11 26  5  0]
 [ 0  0  3  5 15  7]
 [ 0  0  1  3  5  5]]




#0 EMDLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.6860       0.1605        0.9151  0.0010  1.1020


      2        0.3517       0.3210        0.7879  0.0010  1.1998


      3        0.1997       0.3951        0.9916  0.0010  1.1508


      4        0.1444       0.4321        0.5465  0.0010  1.2158


      5        0.0759       0.4074        0.6267  0.0010  0.9851


      6        0.0441       0.4198        0.5939  0.0010  1.0456


      7        0.0186       0.5185        0.4455  0.0010  0.9796


      8        0.0088       0.4938        0.4764  0.0010  1.1753


      9        0.0052       0.5185        0.5149  0.0010  1.0832


     10        0.0036       0.5185        0.5093  0.0010  1.1285


     11        0.0018       0.5062        0.4978  0.0010  1.2923


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 89 / 201 (0.4427860696517413)
ACC: 0.5920398009950248
1OFF: 0.9552238805970149
MAE: 0.4626865671641791
QWK: 0.8598974959730561
AMAE: 0.5253607503607504
MMAE: 1.0714285714285714
RPS: 0.40328313367528934
Unimodality: 0.4427860696517413
[[21  1  0  0  0  0]
 [14 43  1  2  0  0]
 [ 1 16  4 12  0  0]
 [ 0  3  5 32  2  0]
 [ 0  0  0 14 15  1]
 [ 0  0  2  1  7  4]]




#1 EMDLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.7078       0.1852        1.5070  0.0010  1.1368


      2        0.3869       0.3210        1.1332  0.0010  1.0315


      3        0.2036       0.4444        0.5818  0.0010  1.1783


      4        0.1146       0.4444        0.6353  0.0010  1.1017


      5        0.0554       0.4815        0.5284  0.0010  1.2450


      6        0.0239       0.5309        0.4700  0.0010  1.0942


      7        0.0100       0.5556        0.4350  0.0010  1.1602


      8        0.0049       0.5926        0.4250  0.0010  1.1734


      9        0.0040       0.5556        0.4482  0.0010  1.0700


     10        0.0007       0.5309        0.4661  0.0010  1.0202


     11        0.0004       0.5309        0.4715  0.0010  1.0297


     12        0.0002       0.5432        0.4702  0.0010  0.9681


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 94 / 201 (0.46766169154228854)
ACC: 0.5920398009950248
1OFF: 0.945273631840796
MAE: 0.47761194029850745
QWK: 0.8368024800708591
AMAE: 0.513023088023088
MMAE: 0.7333333333333333
RPS: 0.3598481091826512
Unimodality: 0.46766169154228854
[[18  4  0  0  0  0]
 [ 5 43 10  2  0  0]
 [ 1  8 11 12  1  0]
 [ 0  2 10 27  3  0]
 [ 0  1  3 11 13  2]
 [ 0  1  0  0  6  7]]




#2 EMDLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.7309       0.2963        1.1006  0.0010  1.0749


      2        0.4072       0.1358        1.7344  0.0010  1.3915


      3        0.2258       0.3457        0.7875  0.0010  1.4611


      4        0.1210       0.5062        0.5915  0.0010  1.2915


      5        0.0634       0.4938        0.5341  0.0010  1.3593


      6        0.0270       0.4815        0.5691  0.0010  1.1140


      7        0.0123       0.5185        0.6069  0.0010  1.1031


      8        0.0074       0.5062        0.5717  0.0010  1.1754


      9        0.0057       0.4568        0.5673  0.0010  1.1673


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 74 / 201 (0.3681592039800995)
ACC: 0.5373134328358209
1OFF: 0.9104477611940298
MAE: 0.582089552238806
QWK: 0.7760438789266653
AMAE: 0.6497474747474747
MMAE: 1.2142857142857142
RPS: 0.44600798416377596
Unimodality: 0.3681592039800995
[[19  3  0  0  0  0]
 [ 7 43  4  5  0  1]
 [ 0 17  4 12  0  0]
 [ 0  3 11 26  2  0]
 [ 0  1  3 13 11  2]
 [ 0  1  1  3  4  5]]




#0 WKLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.6184       0.1975        0.6266  0.0010  1.4626


      2        0.2402       0.2469        0.4335  0.0010  1.1882


      3        0.1848       0.2840        0.4812  0.0010  1.0861


      4        0.1378       0.3086        0.2748  0.0010  1.0723


      5        0.1048       0.2716        0.3388  0.0010  1.0525


      6        0.0801       0.3333        0.2608  0.0010  1.2795


      7        0.0561       0.5432        0.1896  0.0010  1.3816


      8        0.0336       0.5432        0.2074  0.0010  1.0078


      9        0.0207       0.6296        0.1551  0.0010  1.1829


     10        0.0133       0.6049        0.1683  0.0010  1.1284


     11        0.0097       0.6173        0.1496  0.0010  1.1344


     12        0.0076       0.5802        0.1585  0.0010  1.1490


     13        0.0054       0.5679        0.1594  0.0010  1.0191


     14        0.0044       0.5802        0.1572  0.0010  1.1456


     15        0.0040       0.5556        0.1612  0.0010  1.1443


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 101 / 201 (0.5024875621890548)
ACC: 0.6517412935323383
1OFF: 0.9502487562189055
MAE: 0.40298507462686567
QWK: 0.8695071506742594
AMAE: 0.4683261183261183
MMAE: 1.0714285714285714
RPS: 0.36030064271376516
Unimodality: 0.5024875621890548
[[20  2  0  0  0  0]
 [ 5 43 10  1  1  0]
 [ 1 10 12 10  0  0]
 [ 0  1  5 34  2  0]
 [ 0  0  2  7 19  2]
 [ 0  0  0  4  7  3]]




#1 WKLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.6184       0.1235        0.9999  0.0010  1.4049


      2        0.2759       0.3210        0.3695  0.0010  1.1663


      3        0.1843       0.2593        0.4716  0.0010  1.0622


      4        0.1445       0.3827        0.2589  0.0010  1.1591


      5        0.1138       0.3704        0.2677  0.0010  1.3058


      6        0.0935       0.4568        0.2323  0.0010  1.1573


      7        0.0682       0.6173        0.1975  0.0010  1.2334


      8        0.0476       0.5556        0.2493  0.0010  1.1761


      9        0.0372       0.5309        0.2431  0.0010  1.1987


     10        0.0297       0.6173        0.2249  0.0010  1.1376


     11        0.0267       0.5556        0.2714  0.0010  1.2867


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 159 / 201 (0.7910447761194029)
ACC: 0.582089552238806
1OFF: 0.9154228855721394
MAE: 0.5174129353233831
QWK: 0.7997821842667977
AMAE: 0.6463203463203463
MMAE: 1.5714285714285714
RPS: 0.4427373840451152
Unimodality: 0.7910447761194029
[[17  5  0  0  0  0]
 [ 4 48  6  2  0  0]
 [ 1 10 14  7  1  0]
 [ 0  2 12 24  4  0]
 [ 0  2  2 12 14  0]
 [ 0  0  1  6  7  0]]




#2 WKLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        0.6076       0.2222        0.7039  0.0010  1.0840


      2        0.2458       0.1358        0.9996  0.0010  1.0991


      3        0.1872       0.3210        0.3739  0.0010  1.0839


      4        0.1430       0.3704        0.3127  0.0010  1.2060


      5        0.1052       0.3704        0.4015  0.0010  1.1114


      6        0.0887       0.4444        0.2418  0.0010  1.1953


      7        0.0734       0.4815        0.2535  0.0010  1.0983


      8        0.0565       0.5185        0.2412  0.0010  1.1149


      9        0.0443       0.4938        0.2233  0.0010  1.0787


     10        0.0331       0.4938        0.2051  0.0010  1.1115


     11        0.0282       0.5185        0.2231  0.0010  0.9575


     12        0.0264       0.4691        0.2555  0.0010  0.9705


     13        0.0253       0.4568        0.2391  0.0010  1.1171


     14        0.0242       0.4568        0.2421  0.0010  1.0153


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 132 / 201 (0.6567164179104478)
ACC: 0.5771144278606966
1OFF: 0.945273631840796
MAE: 0.47761194029850745
QWK: 0.8419137250719846
AMAE: 0.5542207792207793
MMAE: 1.2857142857142858
RPS: 0.4335660448280741
Unimodality: 0.6567164179104478
[[19  3  0  0  0  0]
 [ 2 43 13  2  0  0]
 [ 0  7 17  8  1  0]
 [ 0  2 15 20  5  0]
 [ 0  0  2 11 17  0]
 [ 0  0  0  4 10  0]]




#0 BinomialLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.8355       0.1358        2.1333  0.0010  1.0665


      2        1.5797       0.2222        2.3957  0.0010  1.1434


      3        1.4758       0.1975        1.9169  0.0010  1.0619


      4        1.4174       0.3580        1.5893  0.0010  0.9901


      5        1.3822       0.4074        1.5602  0.0010  1.0493


      6        1.3650       0.4198        1.5164  0.0010  1.0904


      7        1.3528       0.4691        1.5328  0.0010  1.0585


      8        1.3474       0.4444        1.5250  0.0010  1.0480


      9        1.3439       0.5432        1.5155  0.0010  1.1017


     10        1.3413       0.5432        1.5148  0.0010  1.2398


     11        1.3398       0.5556        1.5138  0.0010  0.9987


     12        1.3389       0.5802        1.5203  0.0010  1.0545


     13        1.3384       0.5432        1.5221  0.0010  1.1145


     14        1.3379       0.5309        1.5241  0.0010  1.0929


     15        1.3376       0.5556        1.5249  0.0010  1.0442


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.5870646766169154
1OFF: 0.9701492537313433
MAE: 0.4427860696517413
QWK: 0.8674306984033695
AMAE: 0.495021645021645
MMAE: 0.8571428571428571
RPS: 0.386791758531616
Unimodality: 1.0
[[15  7  0  0  0  0]
 [ 1 44 13  2  0  0]
 [ 1  6 15 11  0  0]
 [ 0  1 12 24  5  0]
 [ 0  0  1 11 17  1]
 [ 0  0  0  1 10  3]]




#1 BinomialLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.8348       0.2222        1.9055  0.0010  1.0537


      2        1.5833       0.2716        3.0392  0.0010  1.1370


      3        1.4573       0.4321        1.7888  0.0010  1.0472


      4        1.4116       0.4198        1.5915  0.0010  1.3032


      5        1.3771       0.4444        1.6164  0.0010  1.1379


      6        1.3623       0.4568        1.5895  0.0010  1.1226


      7        1.3517       0.5062        1.5497  0.0010  1.1668


      8        1.3450       0.6049        1.5151  0.0010  1.0451


      9        1.3406       0.6420        1.4993  0.0010  1.0992


     10        1.3389       0.6296        1.5024  0.0010  1.0896


     11        1.3372       0.6543        1.4890  0.0010  1.0805


     12        1.3363       0.6296        1.4828  0.0010  1.0884


     13        1.3357       0.6296        1.4837  0.0010  1.0653


     14        1.3352       0.6543        1.4846  0.0010  1.2411


     15        1.3350       0.6543        1.4822  0.0010  1.0812


     16        1.3348       0.6667        1.4814  0.0010  1.1099


     17        1.3346       0.6543        1.4801  0.0010  1.0054


     18        1.3345       0.6543        1.4817  0.0010  1.1897


     19        1.3344       0.6420        1.4824  0.0010  1.2015


     20        1.3344       0.6543        1.4818  0.0010  1.1209


     21        1.3343       0.6667        1.4817  0.0010  1.2470


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.6069651741293532
1OFF: 0.9651741293532339
MAE: 0.43283582089552236
QWK: 0.8677324943752625
AMAE: 0.4753246753246753
MMAE: 0.9285714285714286
RPS: 0.3701666795768305
Unimodality: 1.0
[[19  3  0  0  0  0]
 [ 5 40 13  2  0  0]
 [ 0 10 13 10  0  0]
 [ 0  3  6 29  4  0]
 [ 0  0  1 10 18  1]
 [ 0  0  1  0 10  3]]




#2 BinomialLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.9331       0.1728        1.9069  0.0010  1.0727


      2        1.6157       0.2963        1.8069  0.0010  1.0241


      3        1.5002       0.3333        1.6980  0.0010  1.0053


      4        1.4332       0.2716        1.6175  0.0010  1.0000


      5        1.3936       0.4074        1.5969  0.0010  1.0581


      6        1.3728       0.4938        1.5572  0.0010  1.1475


      7        1.3554       0.3827        1.5761  0.0010  1.0539


      8        1.3495       0.4938        1.5342  0.0010  1.0783


      9        1.3441       0.5185        1.5364  0.0010  1.1999


     10        1.3428       0.5062        1.5367  0.0010  1.1483


     11        1.3400       0.5309        1.5277  0.0010  1.1370


     12        1.3393       0.4568        1.5257  0.0010  0.9854


     13        1.3386       0.4691        1.5282  0.0010  1.0793


     14        1.3381       0.4691        1.5228  0.0010  1.1114


     15        1.3377       0.5062        1.5296  0.0010  1.0441


     16        1.3372       0.4568        1.5243  0.0010  1.0375


     17        1.3371       0.4938        1.5268  0.0010  1.0400


     18        1.3370       0.4568        1.5252  0.0010  1.0150


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 201 / 201 (1.0)
ACC: 0.6467661691542289
1OFF: 0.9402985074626866
MAE: 0.4228855721393035
QWK: 0.8440468661368037
AMAE: 0.5066738816738817
MMAE: 1.1428571428571428
RPS: 0.38987451202647366
Unimodality: 1.0
[[17  5  0  0  0  0]
 [ 2 44 11  3  0  0]
 [ 0  7 17  8  1  0]
 [ 0  1  7 33  1  0]
 [ 0  0  5  6 17  2]
 [ 0  1  0  1 10  2]]




#0 TriangularLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.6988       0.3457        2.1946  0.0010  0.9793


      2        0.9538       0.4074        1.4719  0.0010  1.0380


      3        0.6119       0.1728        4.7909  0.0010  1.0788


      4        0.4905       0.4938        1.4018  0.0010  1.1525


      5        0.4116       0.4321        1.4812  0.0010  1.0437


      6        0.3820       0.5062        1.3985  0.0010  0.9463


      7        0.3719       0.5679        1.2601  0.0010  0.9752


      8        0.3594       0.5185        1.3559  0.0010  1.0425


      9        0.3550       0.5802        1.3490  0.0010  1.1199


     10        0.3514       0.5802        1.2542  0.0010  1.0834


     11        0.3497       0.5926        1.2250  0.0010  1.2052


     12        0.3483       0.5802        1.2232  0.0010  1.1960


     13        0.3474       0.5679        1.2277  0.0010  1.2992


     14        0.3468       0.5556        1.2280  0.0010  1.0633


     15        0.3465       0.5309        1.2379  0.0010  1.2091


     16        0.3462       0.5432        1.2309  0.0010  1.2613


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 160 / 201 (0.7960199004975125)
ACC: 0.6417910447761194
1OFF: 0.9601990049751243
MAE: 0.4079601990049751
QWK: 0.8716808928191426
AMAE: 0.45750360750360747
MMAE: 0.8571428571428571
RPS: 0.2949980654264855
Unimodality: 0.7960199004975125
[[19  3  0  0  0  0]
 [ 6 45  8  1  0  0]
 [ 0 13  6 14  0  0]
 [ 0  2  4 30  6  0]
 [ 0  0  1  7 21  1]
 [ 0  1  0  3  2  8]]




#1 TriangularLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.6894       0.3704        2.6167  0.0010  1.1287


      2        1.0156       0.2963        1.9402  0.0010  1.2209


      3        0.6370       0.3457        1.6850  0.0010  1.2048


      4        0.4877       0.4444        1.4591  0.0010  1.1309


      5        0.4251       0.4074        1.8230  0.0010  1.1130


      6        0.3908       0.4568        1.4408  0.0010  1.1658


      7        0.3722       0.5556        1.2474  0.0010  1.0139


      8        0.3629       0.5802        1.1660  0.0010  1.0461


      9        0.3553       0.5802        1.1296  0.0010  1.2404


     10        0.3517       0.6049        1.1121  0.0010  1.0597


     11        0.3490       0.6296        1.1113  0.0010  1.2411


     12        0.3474       0.5432        1.1144  0.0010  1.1794


     13        0.3464       0.6049        1.1191  0.0010  0.9937


     14        0.3456       0.6173        1.1270  0.0010  1.2474


     15        0.3451       0.5679        1.1298  0.0010  1.0721


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 151 / 201 (0.7512437810945274)
ACC: 0.6467661691542289
1OFF: 0.9601990049751243
MAE: 0.39303482587064675
QWK: 0.8868317025324333
AMAE: 0.40851370851370855
MMAE: 0.8484848484848485
RPS: 0.2956721398995615
Unimodality: 0.7512437810945274
[[21  1  0  0  0  0]
 [ 2 50  4  4  0  0]
 [ 0 14  5 14  0  0]
 [ 0  3  4 30  5  0]
 [ 0  0  1 10 17  2]
 [ 0  0  0  0  7  7]]




#2 TriangularLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.6842       0.3210        3.5594  0.0010  1.2878


      2        0.9931       0.3580        2.5586  0.0010  1.1542


      3        0.5926       0.3951        2.3450  0.0010  1.1649


      4        0.4437       0.4444        2.2917  0.0010  1.0632


      5        0.4082       0.4321        2.1003  0.0010  1.1408


      6        0.3813       0.4938        1.7047  0.0010  1.2206


      7        0.3695       0.4691        1.6094  0.0010  1.0766


      8        0.3589       0.4938        1.5068  0.0010  1.0997


      9        0.3535       0.5556        1.3768  0.0010  1.3249


     10        0.3509       0.5432        1.3627  0.0010  1.0916


     11        0.3487       0.5432        1.3724  0.0010  1.1662


     12        0.3476       0.5309        1.3536  0.0010  1.2579


     13        0.3468       0.5185        1.3369  0.0010  1.2567


     14        0.3462       0.5556        1.3317  0.0010  1.0027


     15        0.3458       0.5309        1.3376  0.0010  1.0206


     16        0.3455       0.5309        1.3530  0.0010  1.1826


     17        0.3453       0.4938        1.3628  0.0010  1.1500


     18        0.3452       0.4938        1.3626  0.0010  1.0866


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 145 / 201 (0.7213930348258707)
ACC: 0.6268656716417911
1OFF: 0.945273631840796
MAE: 0.4427860696517413
QWK: 0.8509180812253143
AMAE: 0.4892857142857143
MMAE: 0.8181818181818182
RPS: 0.32600038652605917
Unimodality: 0.7213930348258707
[[18  4  0  0  0  0]
 [ 2 51  4  2  1  0]
 [ 0 13  8 10  2  0]
 [ 0  1  9 26  6  0]
 [ 0  2  1  8 17  2]
 [ 0  0  0  2  6  6]]




#0 BetaLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.7213       0.3210        1.8583  0.0010  1.3786


      2        1.2634       0.1852        2.3525  0.0010  1.2091


      3        1.0592       0.3086        1.7349  0.0010  1.0923


      4        0.9257       0.4444        1.4545  0.0010  1.1189


      5        0.8665       0.5309        1.3214  0.0010  1.1467


      6        0.8340       0.5309        1.3377  0.0010  1.1294


      7        0.8190       0.5802        1.2971  0.0010  1.2557


      8        0.8102       0.5309        1.2892  0.0010  1.1839


      9        0.8048       0.5679        1.2891  0.0010  1.1967


     10        0.8020       0.5802        1.3013  0.0010  1.1952


     11        0.8000       0.5802        1.2928  0.0010  1.0667


     12        0.7984       0.5432        1.2985  0.0010  1.1396


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 192 / 201 (0.9552238805970149)
ACC: 0.6218905472636815
1OFF: 0.9701492537313433
MAE: 0.4129353233830846
QWK: 0.8798347796155728
AMAE: 0.4549062049062049
MMAE: 0.7878787878787878
RPS: 0.30082644170949296
Unimodality: 0.9552238805970149
[[17  5  0  0  0  0]
 [ 3 47  8  1  1  0]
 [ 0 14  8 10  1  0]
 [ 0  1  9 25  7  0]
 [ 0  0  1  4 24  1]
 [ 0  0  0  1  9  4]]




#1 BetaLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.7497       0.2963        2.3779  0.0010  1.1401


      2        1.2693       0.3086        2.2683  0.0010  1.2048


      3        1.0415       0.3210        1.9642  0.0010  1.3067


      4        0.9294       0.5679        1.4888  0.0010  1.2632


      5        0.8644       0.4568        1.6134  0.0010  1.2352


      6        0.8291       0.5309        1.5114  0.0010  1.1976


      7        0.8153       0.6543        1.4041  0.0010  1.2042


      8        0.8075       0.6049        1.3966  0.0010  1.3411


      9        0.8024       0.6173        1.3271  0.0010  1.2188


     10        0.7991       0.6296        1.3619  0.0010  1.1765


     11        0.7973       0.6173        1.3323  0.0010  1.1629


     12        0.7959       0.5926        1.3116  0.0010  1.3621


     13        0.7953       0.6049        1.3097  0.0010  1.1329


     14        0.7948       0.5926        1.3154  0.0010  1.0851


     15        0.7944       0.6049        1.3259  0.0010  1.0682


     16        0.7941       0.6049        1.3245  0.0010  1.0467


     17        0.7939       0.5926        1.3185  0.0010  1.0770


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 190 / 201 (0.945273631840796)
ACC: 0.6766169154228856
1OFF: 0.9651741293532339
MAE: 0.3681592039800995
QWK: 0.8799648998793433
AMAE: 0.4336219336219336
MMAE: 0.9285714285714286
RPS: 0.2876443993600556
Unimodality: 0.945273631840796
[[22  0  0  0  0  0]
 [ 2 52  4  2  0  0]
 [ 0 12 10 11  0  0]
 [ 0  2  6 31  3  0]
 [ 0  0  1 11 16  2]
 [ 0  1  0  1  7  5]]




#2 BetaLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.7685       0.2963        2.7839  0.0010  1.0498


      2        1.2626       0.3086        2.4329  0.0010  1.0519


      3        1.0661       0.2716        2.4782  0.0010  1.0962


      4        0.9230       0.3333        1.6896  0.0010  1.0277


      5        0.8669       0.3827        1.5955  0.0010  1.1337


      6        0.8340       0.4938        1.4754  0.0010  0.9727


      7        0.8178       0.4444        1.4471  0.0010  0.9417


      8        0.8095       0.5185        1.4792  0.0010  1.1980


      9        0.8043       0.5556        1.4325  0.0010  1.1588


     10        0.8012       0.5309        1.4683  0.0010  1.0692


     11        0.7989       0.5802        1.4478  0.0010  1.1180


     12        0.7973       0.5556        1.4341  0.0010  1.0808


     13        0.7966       0.5556        1.4310  0.0010  1.1423


     14        0.7959       0.5556        1.4485  0.0010  1.1422


     15        0.7955       0.5556        1.4537  0.0010  1.0646


     16        0.7952       0.5556        1.4442  0.0010  1.1861


     17        0.7950       0.5556        1.4565  0.0010  1.1297


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 150 / 201 (0.746268656716418)
ACC: 0.6019900497512438
1OFF: 0.945273631840796
MAE: 0.472636815920398
QWK: 0.8321383721721487
AMAE: 0.5223304473304474
MMAE: 1.0714285714285714
RPS: 0.34382458747929956
Unimodality: 0.746268656716418
[[22  0  0  0  0  0]
 [ 3 44  9  3  1  0]
 [ 0 10 13  9  1  0]
 [ 0  1 13 23  5  0]
 [ 0  1  1 11 15  2]
 [ 0  1  0  2  7  4]]




#0 GeometricLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.7920       0.3086        1.9329  0.0010  1.1777


      2        1.3850       0.3210        2.4096  0.0010  1.2014


      3        1.2369       0.3210        1.7977  0.0010  1.1428


      4        1.1231       0.4691        1.5390  0.0010  1.1601


      5        1.0626       0.4444        1.5282  0.0010  1.0911


      6        1.0334       0.4815        1.4494  0.0010  0.9890


      7        1.0180       0.5185        1.4282  0.0010  0.9868


      8        1.0107       0.4938        1.4391  0.0010  1.0765


      9        1.0056       0.4938        1.4170  0.0010  1.0675


     10        1.0032       0.5309        1.3992  0.0010  1.1464


     11        1.0013       0.5309        1.3995  0.0010  1.2064


     12        1.0003       0.5185        1.3882  0.0010  1.2083


     13        0.9996       0.5185        1.3843  0.0010  1.0983


     14        0.9992       0.5309        1.3835  0.0010  1.0354


     15        0.9988       0.5185        1.3811  0.0010  1.0880


     16        0.9986       0.5185        1.3795  0.0010  1.1322


     17        0.9984       0.5062        1.3793  0.0010  1.1706


     18        0.9983       0.5185        1.3794  0.0010  1.1317


     19        0.9982       0.5062        1.3792  0.0010  1.1328


     20        0.9982       0.5062        1.3782  0.0010  1.1525


     21        0.9981       0.5185        1.3779  0.0010  1.0903


     22        0.9981       0.5062        1.3793  0.0010  1.0671


     23        0.9981       0.5062        1.3795  0.0010  0.9979


     24        0.9980       0.5062        1.3798  0.0010  1.0361


     25        0.9980       0.5062        1.3794  0.0010  1.0008


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 197 / 201 (0.9800995024875622)
ACC: 0.5920398009950248
1OFF: 0.9751243781094527
MAE: 0.44776119402985076
QWK: 0.8574343914488011
AMAE: 0.5127705627705628
MMAE: 0.9285714285714286
RPS: 0.3282029890614772
Unimodality: 0.9800995024875622
[[16  6  0  0  0  0]
 [ 4 45 10  1  0  0]
 [ 0 16  6 11  0  0]
 [ 0  1 10 28  3  0]
 [ 0  1  1  7 20  1]
 [ 0  1  0  0  9  4]]




#1 GeometricLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.7991       0.3580        1.8797  0.0010  1.0639


      2        1.4004       0.2963        2.1802  0.0010  1.0544


      3        1.2139       0.2716        1.7834  0.0010  1.0405


      4        1.1268       0.3951        1.7275  0.0010  1.0953


      5        1.0678       0.4815        1.5657  0.0010  1.1037


      6        1.0332       0.5679        1.4481  0.0010  1.1450


      7        1.0187       0.6296        1.3753  0.0010  1.1328


      8        1.0087       0.6049        1.3638  0.0010  1.0006


      9        1.0042       0.5802        1.3753  0.0010  0.9905


     10        1.0005       0.5926        1.3653  0.0010  1.1544


     11        0.9992       0.5679        1.3479  0.0010  1.1206


     12        0.9975       0.6296        1.3417  0.0010  1.0471


     13        0.9968       0.5926        1.3360  0.0010  1.0837


     14        0.9959       0.6049        1.3322  0.0010  1.1815


     15        0.9957       0.5556        1.3341  0.0010  1.1531


     16        0.9954       0.5556        1.3339  0.0010  1.0331


     17        0.9952       0.6049        1.3297  0.0010  1.1599


     18        0.9950       0.6173        1.3271  0.0010  1.1276


     19        0.9950       0.6173        1.3264  0.0010  1.2205


     20        0.9949       0.6296        1.3296  0.0010  1.0902


     21        0.9948       0.6173        1.3277  0.0010  1.0723


     22        0.9948       0.6420        1.3274  0.0010  1.1619


     23        0.9948       0.6420        1.3272  0.0010  1.1778


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 199 / 201 (0.9900497512437811)
ACC: 0.6766169154228856
1OFF: 0.9701492537313433
MAE: 0.35323383084577115
QWK: 0.9003148957020023
AMAE: 0.379978354978355
MMAE: 0.7272727272727273
RPS: 0.30266548606817667
Unimodality: 0.9900497512437811
[[21  1  0  0  0  0]
 [ 4 49  5  2  0  0]
 [ 0 16  9  8  0  0]
 [ 0  3  5 33  1  0]
 [ 0  0  1  9 18  2]
 [ 0  0  0  0  8  6]]




#2 GeometricLoss


  epoch    train_loss    valid_acc    valid_loss      lr     dur
-------  ------------  -----------  ------------  ------  ------
      1        1.8140       0.3086        2.2368  0.0010  1.0675


      2        1.4177       0.3086        2.0621  0.0010  1.1155


      3        1.2407       0.2716        1.9120  0.0010  1.2912


      4        1.1148       0.2716        1.7507  0.0010  1.2416


      5        1.0634       0.4321        1.5335  0.0010  1.2442


      6        1.0299       0.4074        1.5190  0.0010  1.2235


      7        1.0156       0.4691        1.4388  0.0010  1.2742


      8        1.0073       0.4938        1.3998  0.0010  1.2173


      9        1.0041       0.4938        1.3797  0.0010  1.1811


     10        1.0015       0.5309        1.3736  0.0010  1.1682


     11        1.0001       0.5432        1.3626  0.0010  1.3209


     12        0.9990       0.5926        1.3406  0.0010  1.0768


     13        0.9985       0.5679        1.3310  0.0010  1.1791


     14        0.9980       0.5802        1.3410  0.0010  1.2131


     15        0.9977       0.5926        1.3443  0.0010  1.2154


     16        0.9976       0.6049        1.3424  0.0010  1.2990


     17        0.9974       0.5926        1.3432  0.0010  1.1779


Stopping since valid_loss has not improved in the last 5 epochs.


Unimodal predictions: 167 / 201 (0.8308457711442786)
ACC: 0.6119402985074627
1OFF: 0.945273631840796
MAE: 0.4626865671641791
QWK: 0.8451964513530833
AMAE: 0.5012626262626263
MMAE: 0.8571428571428571
RPS: 0.3399406574533875
Unimodality: 0.8308457711442786
[[22  0  0  0  0  0]
 [ 4 47  6  2  1  0]
 [ 0 13  8 12  0  0]
 [ 0  3  8 25  6  0]
 [ 0  2  1  7 16  4]
 [ 0  0  1  1  7  5]]




## Result
Displays the mean results for each loss over the K iterations.

In [5]:
result.set_index(["loss", "iteration"], inplace=True)
result.groupby("loss").agg("mean").style.highlight_max(
    axis=0, subset=["ACC", "1OFF", "QWK"], color="green"
).highlight_min(axis=0, subset=["MAE", "AMAE", "MMAE", "RPS"], color="green")